In [1]:
import numpy as np 
import torch

batch_size = 5 

At first we have : 
- camera's parameters -> A (focal, center) 
- rotation matrix  -> R 
- position matrix -> C 
- 3D points position ->  P1 P2 P3 (and P4 to determinate the best solution after P3P)

In [2]:
# This script defines the camera parameters, rotation matrix, and translation matrix.
def camera() : 
  # Definition of the camera parameters
  # focal length
  fx = 800
  fy = 800
  # center
  cx = 320 
  cy = 240

  A = torch.tensor([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=torch.float64) # intraseca matrix of the camera (3*3)
  #A = torch.from_numpy(A)  # Convert to a PyTorch tensor
  print("A = \n", A)
  print(A.shape)  # (3*3)
  A_batch = A.repeat(batch_size,1,1)
  print("A_batch = \n", A_batch)
  print(A_batch.shape)  # (batch_size, 3, 3)
  return A_batch

A = camera() 



def rotation_matrix() : 
  # Definition of the rotation matrix of the camera 
  R = torch.tensor([[1, 0, 0],[0, -1, 0], [0, 0, -1]], dtype=torch.float64)  # (3*3)
  #R = torch.from_numpy(R)  # Convert to a PyTorch tensor
  print("R = \n",R)
  print(R.shape)  # (3*3)
  R_batch = R.repeat(batch_size,1,1)  # Repeat the rotation matrix for each batch
  print("R_batch = \n", R_batch)  
  print(R_batch.shape)  # (batch_size, 3, 3)
  return R_batch

def camera_position() : 
  # Definition of the translation matrix of the camera (the position)
  C = torch.tensor([[0,0,6]], dtype=torch.float64)    # T = [tx,ty,tz]  (1*3)
  print("C = \n",C)
  print(C.shape)  # (1*3)

  C_batch = C.repeat(batch_size, 1)  # Repeat the translation vector for each batch
  print("C_batch = \n", C_batch)  
  print(C_batch.shape)  # (batch_size, 3)

 
  return C_batch

R = rotation_matrix()
C = camera_position()

A = 
 tensor([[800.,   0., 320.],
        [  0., 800., 240.],
        [  0.,   0.,   1.]], dtype=torch.float64)
torch.Size([3, 3])
A_batch = 
 tensor([[[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]]], dtype=torch.float64)
torch.Size([5, 3, 3])
R = 
 tensor([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]], dtype=torch.float64)
torch.Size([3, 3])
R_batch = 
 tensor([[[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.

In [3]:
# Definition of 3D points in the world coordinate system
def point3Daleatoire(x) :
  # Generation of one random points in 3D space 
  return torch.tensor([[np.random.uniform(-x,x),np.random.uniform(-x,x),np.random.uniform(-x,x)]])

def pts_3D_4pts():
  # Generate randomly 4 3D points
  # Output : tensor which concatenate the 4 points = [ P1, P2, P3, P4 ] 

  P1 = point3Daleatoire(2)     # (1*3) -> pour P3P
  P2 = point3Daleatoire(2)
  P3 = point3Daleatoire(2)
  P4 = point3Daleatoire(2)
  
  points3D = torch.cat((P1,P2,P3,P4),dim=0);     # (LIGNES 4* COLONNES 3) - xyz
  print("points3D = \n", points3D)
  print(points3D.shape)  # (4*3)

  
  return points3D

def pts_3D_4pts_batch():
  # Generate randomly 4 3D points for each batch
  # Output : array which concatenate the 4 points = [ P1, P2, P3, P4 ] for each batch

  # Generate a batch of random points in 3D space
  # Each point is generated independently for each batch

  points3D_batch = torch.stack([pts_3D_4pts() for i in range(batch_size)])  # (batch_size, 4, 3)
  print("points3D_batch = \n", points3D_batch)
  print(points3D_batch.shape)  # (batch_size, 4, 3)
  return points3D_batch

points3D_batch = pts_3D_4pts_batch()  # Generate the batch of 3D points
'''
P1 = torch.tensor([0.7161, 0.5431, 1.7807], dtype=torch.float64)    # (3,)
P2 = torch.tensor([-1.1643, 0.8371, -1.0551], dtype=torch.float64)
P3 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64)
P4 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64) 
'''
P1 = points3D_batch[:, 0, :]  # Extract P1 for each batch
P2 = points3D_batch[:, 1, :]  # Extract P2 for each batch
P3 = points3D_batch[:, 2, :]  # Extract P3 for each batch
P4 = points3D_batch[:, 3, :]  # Extract P4 for each batch

print("P1 = \n", P1)
print(P1.shape)  # (batch_size, 3)


points3D = 
 tensor([[-0.7377, -1.1455, -1.6429],
        [ 1.8482,  0.5916, -1.3284],
        [-0.4843, -0.2586,  1.4970],
        [ 0.3157, -1.8951, -0.9283]])
torch.Size([4, 3])
points3D = 
 tensor([[ 0.2829,  0.2174,  0.1789],
        [ 1.8947, -0.1436,  0.7514],
        [-1.1003,  0.0483, -1.6930],
        [-1.5286, -1.3628, -1.8271]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.1478, -0.3473,  1.9207],
        [-1.9916, -0.2563,  1.9493],
        [-1.6165,  0.0384,  1.7855],
        [ 1.3904, -1.4125,  1.9788]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.4346,  0.0487,  1.8657],
        [-0.6365,  1.3466, -0.1124],
        [-1.7585, -0.3124,  1.0408],
        [-0.2311,  0.8440,  1.8143]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.0505, -1.6277, -1.7226],
        [ 0.8749,  0.7473,  1.3001],
        [ 0.3502,  1.4500,  1.0111],
        [ 0.1903, -1.4913,  1.0150]])
torch.Size([4, 3])
points3D_batch = 
 tensor([[[-0.7377, -1.1455, -1.6429],
         [ 1.8482,  0.5916, -1.3284],


We create the 3 direction features vectors f1, f2, f3

In [4]:
def features_vectors(points3D,C, R,batch_size) :
    '''
    This function computes the features vectors for P3P algorithm.
    args:
    points3D : array with the 4 3D points = [ P1, P2, P3, P4 ] (4*3) 
    but we only use the first three points for P3P
    C: camera position matrix : (3*1)
    returns:
    featuresVect : array with the features vectors (9*1)
    '''
    P1 = torch.reshape(points3D[0], (batch_size,3,1))  # Reshape to (3,1) for easier calculations
    print("P1 = \n", P1)  # Print P1 to check the values
    print(P1.shape)  # (batch_size, 3, 1)
    P2 = torch.reshape(points3D[1], (batch_size,3,1))
    P3 = torch.reshape(points3D[2], (batch_size,3,1))

    C = torch.reshape(C, (batch_size,3,1))  # Reshape C to (3,1) for easier calculations
    print("C = \n", C)  # Print C to check the values
    print(C.shape)  # (batch_size, 3, 1)

    v1 = torch.matmul(R,(P1 - C))  # Calculate the vector from camera to P1
    print("v1 = \n", v1)  # Print v1 to check the values
    print(v1.shape)  # (batch_size, 3, 1)
    v2 = torch.matmul(R,(P2 - C))  # Calculate the vector from camera to P2
    v3 = torch.matmul(R,(P3 - C))  # Calculate the vector from camera to P3

    f1 = v1 / torch.norm(v1,dim=1, keepdim=True)  # Normalize the vector v1
    f2 = v2 / torch.norm(v2,dim=1, keepdim=True)  # Normalize the vector v2
    f3 = v3 / torch.norm(v3,dim=1, keepdim=True)  # Normalize the vector v3

    print("f1 = \n", f1)  # Print f1 to check the values
    print(f1.shape)  # (batch_size, 3, 1)

    f1 = torch.reshape(f1, (batch_size,1,3))  # Reshape to (3,1)
    print("f1 : ",f1.shape) # (batch_size,1,3)
    f2 = torch.reshape(f2, (batch_size,1,3))
    f3 = torch.reshape(f3, (batch_size,1,3))

    featuresVect = torch.cat((f1,f2,f3),dim=1)
    print("features vectors = \n",featuresVect)
    print(featuresVect.shape)  # (batch_size, 3, 3)

    return featuresVect # Return the features vectors need in P3P


points3D = [P1, P2, P3]  # We define the points3D with the first three points
print("points3D = \n", points3D)  # Print the points3D to check the values  / List len = 3 


featuresVect = features_vectors(points3D, C, R,batch_size)  

points3D = 
 [tensor([[-0.7377, -1.1455, -1.6429],
        [ 0.2829,  0.2174,  0.1789],
        [-1.1478, -0.3473,  1.9207],
        [-1.4346,  0.0487,  1.8657],
        [-1.0505, -1.6277, -1.7226]]), tensor([[ 1.8482,  0.5916, -1.3284],
        [ 1.8947, -0.1436,  0.7514],
        [-1.9916, -0.2563,  1.9493],
        [-0.6365,  1.3466, -0.1124],
        [ 0.8749,  0.7473,  1.3001]]), tensor([[-0.4843, -0.2586,  1.4970],
        [-1.1003,  0.0483, -1.6930],
        [-1.6165,  0.0384,  1.7855],
        [-1.7585, -0.3124,  1.0408],
        [ 0.3502,  1.4500,  1.0111]])]
P1 = 
 tensor([[[-0.7377],
         [-1.1455],
         [-1.6429]],

        [[ 0.2829],
         [ 0.2174],
         [ 0.1789]],

        [[-1.1478],
         [-0.3473],
         [ 1.9207]],

        [[-1.4346],
         [ 0.0487],
         [ 1.8657]],

        [[-1.0505],
         [-1.6277],
         [-1.7226]]])
torch.Size([5, 3, 1])
C = 
 tensor([[[0.],
         [0.],
         [6.]],

        [[0.],
         [0.],
   

Lastly we need the functions to resolve the polynomial roots. - for test go to test resolution polynome 

In [ ]:
from complex_batch_utils import *
import complex_utils as cpu
from torch import vmap

def polynomial_root_calculation_3rd_degree(a, b, c, d):
    # a (batch_size, 1)
    # b (batch_size, 1)
    # c (batch_size, 1)
    # d (batch_size, 1)
    batch_size = a.shape[0]  # Get the batch size from the shape of a
    '''# Convert to complex tensors
    a = torch.tensor(a, dtype=torch.complex64)
    b = torch.tensor(b, dtype=torch.complex64)
    c = torch.tensor(c, dtype=torch.complex64)
    d = torch.tensor(d, dtype=torch.complex64)'''

    # Discriminant terms
    p = (3 * a * c - b**2) / (3 * a**2)     # (batch_size, 1) because element-wise opeations
    q = (2 * b**3 - 9 * a * b * c + 27 * a**2 * d) / (27 * a**3)    # bathch_size, 1)
    print("q : ",q.shape)  # (batch_size, 1)
    delta = -4 * p**3 - 27 * q**2   # (batch_size, 1)
    print("delta : ",delta.shape)
    roots = []

    j_ = torch.tensor([-0.5, torch.sqrt(torch.tensor(3))/2])  # cube root of unity
    
    for k in range (3):
        delta_sur_27 = -delta / 27   #(batch_size, 1) 
        print("delta_sur_27 :", delta_sur_27.shape)

        sqrt_term = sqrt_batch(delta_sur_27)  
        print("sqrt_term = \n", sqrt_term[:,0].unsqueeze(-1).shape)

        # faire une seule fois les calculs de j^k et j^-k
        j_exp_k = cpu.complex_number_power_k(j_, k)  # Compute j^k for each batch
        j_exp_moins_k = cpu.complex_number_power_k(j_, -k)  # Compute j^-k for each batch

        j_exp_k_batch = j_exp_k.repeat(batch_size, 1)
        j_exp_moins_k_batch = j_exp_moins_k.repeat(batch_size, 1)

        u_k = product_of_2_complex_numbers_batch(j_exp_k_batch, sqrt_3_batch(torch.stack([0.5*(-q.squeeze()+sqrt_term[:,0]),sqrt_term[:,1]],dim=-1)) )
        print("u_k",u_k.shape)  # (batch_size, 2) 
        v_k = product_of_2_complex_numbers_batch(j_exp_moins_k_batch, sqrt_3_batch(torch.stack([0.5*(-q.squeeze()-sqrt_term[:,0]),-0.5*sqrt_term[:,1]],dim=-1)))
        print("v_k",v_k.shape)  # (batch_size, 2) 

        root = addition_batch(addition_batch(u_k, v_k), torch.stack([-b[:,0]/(3*a[:,0]),0.0*b[:,0]],dim=-1) ) 
        print("root = \n", root)  # Print root to check the values
        print(root.shape)  # (batch_size, 2) for complex numbers
        roots.append(root)

    return torch.stack(roots)

batch_size = 6  # Define the batch size
a = torch.rand(batch_size, 1, dtype=torch.float64)  # Random coefficients for the polynomial
b = torch.rand(batch_size, 1, dtype=torch.float64)  # Random coefficients for the polynomial
c = torch.rand(batch_size, 1, dtype=torch.float64)  # Random coefficients   # for the polynomial
d = torch.rand(batch_size, 1, dtype=torch.float64)  # Random coefficients

print(polynomial_root_calculation_3rd_degree(a, b, c, d)) 

q :  torch.Size([6, 1])
delta :  torch.Size([6, 1])
delta_sur_27 : torch.Size([6, 1])
sqrt_term = 
 torch.Size([6, 1])
u_k torch.Size([6, 2])
v_k torch.Size([6, 2])
root = 
 tensor([[-1.2038,  0.0000],
        [-0.7188,  0.0000],
        [-0.3345,  0.0000],
        [-1.0888,  0.0000],
        [-1.3794,  0.0000],
        [-1.2501,  0.0000]], dtype=torch.float64)
torch.Size([6, 2])
delta_sur_27 : torch.Size([6, 1])
sqrt_term = 
 torch.Size([6, 1])
u_k torch.Size([6, 2])
v_k torch.Size([6, 2])
root = 
 tensor([[ 0.1743,  1.0615],
        [ 0.2201,  1.2364],
        [-0.1127,  0.7158],
        [ 0.0514,  0.5628],
        [-0.2776,  1.4273],
        [-0.1040,  0.0972]], dtype=torch.float64)
torch.Size([6, 2])
delta_sur_27 : torch.Size([6, 1])
sqrt_term = 
 torch.Size([6, 1])
u_k torch.Size([6, 2])
v_k torch.Size([6, 2])
root = 
 tensor([[ 0.1743, -1.0615],
        [ 0.2201, -1.2364],
        [-0.1127, -0.7158],
        [ 0.0514, -0.5628],
        [-0.2776, -1.4273],
        [-0.1040, -0.097

In [ ]:

def polynomial_root_calculation_4th_degree_ferrari(a): # Ferrari's Method
    # Solving a polynomial of 4th degree

    # Input : array 5*1 with the 5 coefficiants of the polynomial 
    # Output : roots of the polynomial a[4]*x^4 + a[3]*x^3 + a[2]*x^2 + a[1]*x + a[0]   -> array : [x1,x2,x3,x4]  (4*1)

    if a.numel() != 5 :
      print("Expeted 5 coefficiants for a 4th order polynomial")
      return

    a0, a1, a2, a3, a4 = a      # float

    # Reduce the quartic equation to the form : x^4 + a*x^3 + b*x^2 + c*x + d = 0
    a = a3/a4           # float 
    b = a2/a4
    c = a1/a4
    d = a0/a4

    # Computation of the coefficients of the Ferrari's Method
    S = a/4
    b0 = d - c*S + b* S**2 - 3* S**4
    b1 = c - 2*b*S + 8*S**3
    b2 = b - 6 * S**2


    # Solve the cubic equation m^3 + b2*m^2 + (b2^2/4  - b0)*m - b1^2/8 = 0
    x_cube = polynomial_root_calculation_3rd_degree(1,b2,(b2**2)/4-b0,(-b1**2)/8)
    

    # Find a real and positive solution
    condition = (torch.isclose(x_cube[:,1],torch.tensor(0.0,dtype=torch.float64),atol=1e-7)) & (x_cube[:,0] > 0) 
    condition_respected = x_cube[condition]  # Get the indices of the roots that respect the condition

    print("indices_respect_condition = \n", condition_respected)  # Print the indices of the roots that respect the condition
    alpha_0_nul = condition_respected.shape[0] == 0
    print("alpha_0_nul = ", alpha_0_nul)  # Print if we found a real and positive solution

    if not alpha_0_nul : 
       alpha_0 = condition_respected[-1]


    if alpha_0_nul == False :   # case where we found a real and positive solution so alpha_0_imag = 0 
        alpha0_div_2 = product_complex_real(alpha_0,0.5)
        sqrt_alpha = sqrt(alpha0_div_2[0])
        term = addition_complex_real(- alpha0_div_2 ,-b2 / 2)
        denom = 2 * torch.sqrt(2 * alpha_0)
        
       
        frac = division_2_complex_numbers(torch.tensor([b1, 0.0]), denom)  # b1 is real, so we can use a tensor with 0 imaginary part

        x1 = addition_complex_real(sqrt_alpha ,- S) + sqrt_complex(addition(term,-frac))
        x2 = addition_complex_real(sqrt_alpha, - S) - sqrt_complex(addition(term,-frac))
        x3 = addition_complex_real(-sqrt_alpha, - S) + sqrt_complex(addition(term,frac))
        x4 = addition_complex_real(-sqrt_alpha,- S) - sqrt_complex(addition(term,frac))
    
    else:

        sqrt_inner1 = sqrt((b2**2) / 4 - b0)        # complex 
        x1 = addition_complex_real(sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x2 = addition_complex_real(- sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x3 = addition_complex_real(sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)
        x4 = addition_complex_real(- sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)

    return torch.tensor([x1, x2, x3, x4])




We have all the variables needed for the p3p so we start

1. Storage of points : already done 

In [ ]:
print("P1 = \n", P1)
print("P2 = \n", P2)
print("P3 = \n", P3)

P1 = 
 tensor([[-0.8029, -0.9789,  0.1435],
        [ 0.9660, -0.2044, -1.6157],
        [-0.5413,  0.5364, -0.6280],
        [ 1.6701,  0.2629,  1.4596],
        [ 1.4211, -1.0685,  1.1588]])
P2 = 
 tensor([[-0.8397,  0.2084, -1.2476],
        [-1.8121,  1.7484, -0.8378],
        [-0.1718, -0.9837,  1.8333],
        [-0.9748, -0.5198,  0.0031],
        [-0.6890, -0.5929,  1.6234]])
P3 = 
 tensor([[-1.3260,  0.8195, -0.8463],
        [ 1.3346,  1.4918,  1.7841],
        [-0.9387,  0.0496, -1.1850],
        [-0.0030,  1.2614,  0.9369],
        [ 1.1602,  1.8517, -0.5021]])


2. Storage of the features vectors : done

In [ ]:
# we got featuresVect and we access the 3 values 
f1 = featuresVect[:,0,:]  # Access the first feature vector for each batch
f2 = featuresVect[:,1,:]
f3 = featuresVect[:,2,:]

print("f1 = ", f1)
print(f1.shape)  # (batsh_size,3)
print("f2 = ", f2)
print(f2.shape)  # (batsh_size,3)
print("f3 = ", f3)
print(f3.shape)  # (batsh_size,3)

f1 =  tensor([[-0.1340,  0.1634,  0.9774],
        [ 0.1258,  0.0266,  0.9917],
        [-0.0811, -0.0804,  0.9935],
        [ 0.3447, -0.0543,  0.9371],
        [ 0.2755,  0.2072,  0.9387]], dtype=torch.float64)
torch.Size([5, 3])
f2 =  tensor([[-0.1150, -0.0285,  0.9930],
        [-0.2487, -0.2399,  0.9384],
        [-0.0401,  0.2296,  0.9725],
        [-0.1599,  0.0852,  0.9835],
        [-0.1541,  0.1326,  0.9791]], dtype=torch.float64)
torch.Size([5, 3])
f3 =  tensor([[-1.8885e-01, -1.1671e-01,  9.7505e-01],
        [ 2.8597e-01, -3.1966e-01,  9.0335e-01],
        [-1.2954e-01, -6.8513e-03,  9.9155e-01],
        [-5.7391e-04, -2.4175e-01,  9.7034e-01],
        [ 1.6914e-01, -2.6995e-01,  9.4790e-01]], dtype=torch.float64)
torch.Size([5, 3])


3. Création of a solution variable : maximum 4 solutions  

    Matrix (4,3,4)  
    Each layer is a solution, for each leayer : first column stres the camera position matrix C (3,1) and the remaining 3 columns store the rotation matrix R (3,3)

In [ ]:
solutions = torch.zeros((batch_size,4,3,4), dtype=torch.float64)
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

solutions = 
 tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
        

4. Verification that the 3 points given are not collinear 

In [ ]:
# Test of non-collinearity
v1 = P2 - P1
print("v1 = \n", v1)  # Print v1 to check the values
print(v1.shape)  # (batch_size, 3)
v2 = P3 - P1

norms = torch.norm(torch.cross(v1,v2, dim=1),dim = 1 )
print("norms : ",norms.shape)  # (batch_size,)

all_dif_zero = torch.all(norms != 0)  # Check if all norms are non-zero

if not all_dif_zero:
    print('\nProblem: the points must not be collinear')
else:
    print('\nThe points are not collinear, we can continue')

v1 = 
 tensor([[-0.0368,  1.1873, -1.3911],
        [-2.7781,  1.9528,  0.7780],
        [ 0.3696, -1.5201,  2.4613],
        [-2.6449, -0.7826, -1.4565],
        [-2.1101,  0.4756,  0.4646]])
torch.Size([5, 3])
norms :  torch.Size([5])

The points are not collinear, we can continue


5. Creation of an orthonormal frame from f1, f2, f3 (the features vectors)

In [ ]:
# Calculation of vectors of the base τ = (C,tx,ty,tz)
tx = f1     
print("tx = ", tx)
print(tx.shape)  # (batch_size,3)

tz = torch.cross(f1,f2,dim=1)/ torch.norm(torch.cross(f1,f2,dim=1),dim=1, keepdim=True)  # Normalize the cross product to get tz
print("tz = ", tz)
print(tz.shape)  # (batch_size,3)

ty = torch.cross(tz,tx,dim=1)
print("ty = ", ty)
print(ty.shape)  # (batch_size,3)

tx =  tensor([[-0.1340,  0.1634,  0.9774],
        [ 0.1258,  0.0266,  0.9917],
        [-0.0811, -0.0804,  0.9935],
        [ 0.3447, -0.0543,  0.9371],
        [ 0.2755,  0.2072,  0.9387]], dtype=torch.float64)
torch.Size([5, 3])
tz =  tensor([[ 0.9873,  0.1070,  0.1175],
        [ 0.5840, -0.8100, -0.0523],
        [-0.9895,  0.1263, -0.0706],
        [-0.2628, -0.9640,  0.0408],
        [ 0.1833, -0.9699,  0.1603]], dtype=torch.float64)
torch.Size([5, 3])
ty =  tensor([[ 0.0854, -0.9807,  0.1757],
        [-0.8019, -0.5858,  0.1174],
        [ 0.1198,  0.9887,  0.0898],
        [-0.9012,  0.2603,  0.3465],
        [-0.9436, -0.1279,  0.3052]], dtype=torch.float64)
torch.Size([5, 3])


5. (bis) Creation of a transformation matrix T and expression of the f3 vector in this frame

In [ ]:
tx = torch.reshape(tx,(batch_size,1,3))   # (batch_sizee,1,3)
print("tx = \n", tx)
print(tx.shape)  # (batch_size,1,3)

ty = torch.reshape(ty,(batch_size,1,3))
print("ty = \n", ty)
print(ty.shape)  # (batch_size,1,3)

tz = torch.reshape(tz,(batch_size,1,3))
print("tz = \n", tz)
print(tz.shape)  # (batch_size,1,3)

# Computation of the matrix T and the feature vector f3
T = torch.cat((tx,ty,tz),dim = 1) # (3*3)
print("T = \n", T)
print(T.shape)  # (batch_size,3,3)


f3_T = torch.matmul(T,f3.unsqueeze(-1)) # (
print("f3_T = \n", f3_T)
print(f3_T.shape)  # (batch_size,3,1)


tx = 
 tensor([[[-0.1340,  0.1634,  0.9774]],

        [[ 0.1258,  0.0266,  0.9917]],

        [[-0.0811, -0.0804,  0.9935]],

        [[ 0.3447, -0.0543,  0.9371]],

        [[ 0.2755,  0.2072,  0.9387]]], dtype=torch.float64)
torch.Size([5, 1, 3])
ty = 
 tensor([[[ 0.0854, -0.9807,  0.1757]],

        [[-0.8019, -0.5858,  0.1174]],

        [[ 0.1198,  0.9887,  0.0898]],

        [[-0.9012,  0.2603,  0.3465]],

        [[-0.9436, -0.1279,  0.3052]]], dtype=torch.float64)
torch.Size([5, 1, 3])
tz = 
 tensor([[[ 0.9873,  0.1070,  0.1175]],

        [[ 0.5840, -0.8100, -0.0523]],

        [[-0.9895,  0.1263, -0.0706]],

        [[-0.2628, -0.9640,  0.0408]],

        [[ 0.1833, -0.9699,  0.1603]]], dtype=torch.float64)
torch.Size([5, 1, 3])
T = 
 tensor([[[-0.1340,  0.1634,  0.9774],
         [ 0.0854, -0.9807,  0.1757],
         [ 0.9873,  0.1070,  0.1175]],

        [[ 0.1258,  0.0266,  0.9917],
         [-0.8019, -0.5858,  0.1174],
         [ 0.5840, -0.8100, -0.0523]],

        [[-0

The sing of the z-coordinate in f3_T give us the sign of teta, that we will need after 

In [ ]:
print(f3_T[:,2])
f3_T_positif = f3_T[:,2] > 0

print("f3_T_positif = \n", f3_T_positif)
print(f3_T_positif.shape)  # (batch_size,1)

tensor([[-0.0844],
        [ 0.3787],
        [ 0.0573],
        [ 0.2728],
        [ 0.4447]], dtype=torch.float64)
f3_T_positif = 
 tensor([[False],
        [ True],
        [ True],
        [ True],
        [ True]])
torch.Size([5, 1])


6. Change of frame is performed on the 3D points side, and the transformation matrix N is defined

In [ ]:
# Calculation of vectors of the base η = (P1,nx,ny,nz)
nx = (P2 - P1)/torch.norm(P2 - P1,dim=1,keepdim=True)      #(batch_size,3)
print("nx : ", nx.shape)  # (batch_size,3)

nz = torch.cross(nx,P3-P1,dim=1)/torch.norm(torch.cross(nx,P3-P1,dim=1), dim=1, keepdim=True) 
print("nz : ", nz.shape)  # (batch_size,3)

ny = torch.cross(nz,nx,dim=1)
print("ny : ", ny.shape)  # (batch_size,3)


# Reshape the vectors to (1,3) for concatenation
nx = torch.reshape(nx,(batch_size,1,3))  # (batch_size,1,3)
ny = torch.reshape(ny,(batch_size,1,3))
nz = torch.reshape(nz,(batch_size,1,3))

print("nx = \n", nx)
print(nx.shape)  # (1*3)
print("ny = \n", ny)
print("nz = \n", nz)

# Computation of the matrix N and the world point P3
N = torch.cat((nx,ny,nz),dim = 1) #  T's equivalent in the world coordinate system
print("N = \n", N)
print(N.shape)  # (batch_size,3,3)

print("P3.shape = ", P3.shape)  # (batch_size,3)

P3_n = torch.matmul(N,(P3-P1).unsqueeze(-1)) 


print("P3_n = \n", P3_n)
print(P3_n.shape)  # (5,3,1)


nx :  torch.Size([5, 3])
nz :  torch.Size([5, 3])
ny :  torch.Size([5, 3])
nx = 
 tensor([[[-0.0201,  0.6491, -0.7605]],

        [[-0.7974,  0.5605,  0.2233]],

        [[ 0.1267, -0.5212,  0.8440]],

        [[-0.8479, -0.2509, -0.4670]],

        [[-0.9538,  0.2150,  0.2100]]])
torch.Size([5, 1, 3])
ny = 
 tensor([[[-0.5553,  0.6253,  0.5484]],

        [[ 0.4225,  0.2546,  0.8699]],

        [[-0.4567, -0.7860, -0.4168]],

        [[-0.3302,  0.9391,  0.0949]],

        [[ 0.0729,  0.8434, -0.5324]]])
nz = 
 tensor([[[ 0.8314,  0.4333,  0.3478]],

        [[ 0.4307,  0.7880, -0.4399]],

        [[ 0.8806, -0.3326, -0.3376]],

        [[ 0.4147,  0.2346, -0.8792]],

        [[-0.2916, -0.4925, -0.8200]]])
N = 
 tensor([[[-0.0201,  0.6491, -0.7605],
         [-0.5553,  0.6253,  0.5484],
         [ 0.8314,  0.4333,  0.3478]],

        [[-0.7974,  0.5605,  0.2233],
         [ 0.4225,  0.2546,  0.8699],
         [ 0.4307,  0.7880, -0.4399]],

        [[ 0.1267, -0.5212,  0.8440],
      

7. Definition of the variables for the following steps 

In [ ]:
# Computation of phi1 et phi2 with 0=x, 1=y, 2=z
phi1 = f3_T[:,0]/f3_T[:,2]
phi2 = f3_T[:,1]/f3_T[:,2]
print("phi1 = ", phi1)
print(phi1.shape)  # (batch_size,1)
print("phi2 = ", phi2)
print(phi2.shape)  # (batch_size,1)

# Extraction of p1 and p2 from P3_eta
p1 = P3_n[:,0] #x
p2 = P3_n[:,1] #y
print("p1 = ", p1)
print(p1.shape)  # (batch_size,3)
print("p2 = ", p2)
print(p2.shape)  # (batch_size,3)

# Computation of d12
d12 = torch.norm(P2-P1,dim=1, keepdim=True) 
print("d12 = ", d12)
print(d12.shape)  # (batch_size,1)

# Computation of b = cot(beta)
cosBeta =( torch.sum(f1*f2,dim=1)/(torch.norm(f1,dim=1)*torch.norm(f2,dim=1)) ).unsqueeze(-1)  # tensor.dot(a,b) <=> tensor.sum(a*b)
print("cosBeta = ", cosBeta)  
print(cosBeta.shape)  # (batch_size,1)

b = torch.sqrt(1/(1-cosBeta**2)-1)
print("b = ", b)
print(b.shape)  # (batch_size,1)

b = torch.where(cosBeta < 0, -b, b)  # If cosBeta < 0, then b = -b
print("b = ", b)
print(b.shape)  # (batch_size,1)

phi1 =  tensor([[-11.3643],
        [  2.4383],
        [ 17.3794],
        [  3.3805],
        [  1.9798]], dtype=torch.float64)
torch.Size([5, 1])
phi2 =  tensor([[-3.1938],
        [ 0.1691],
        [ 1.1645],
        [ 1.0038],
        [ 0.3694]], dtype=torch.float64)
torch.Size([5, 1])
p1 =  tensor([[ 1.9306],
        [ 1.4161],
        [-0.2668],
        [ 1.4122],
        [ 0.5278]])
torch.Size([5, 1])
p2 =  tensor([[0.8722],
        [3.5449],
        [0.7962],
        [1.4406],
        [3.3280]])
torch.Size([5, 1])
d12 =  tensor([[1.8293],
        [3.4837],
        [2.9164],
        [3.1192],
        [2.2123]])
torch.Size([5, 1])
cosBeta =  tensor([[0.9813],
        [0.8929],
        [0.9509],
        [0.8619],
        [0.9041]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[5.0954],
        [1.9835],
        [3.0722],
        [1.6998],
        [2.1156]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[5.0954],
        [1.9835],
        [3.0722],
        [1.6998]

8. Calculation of the coefficients of the polynomial 

In [ ]:
a4 = - phi2**2 * p2**4 - phi1**2 * p2**4 - p2**4
a3 = 2 * p2**3 * d12 * b + 2 * phi2**2 * p2**3 * d12 * b - 2 * phi1 * phi2 * p2**3 * d12
a2 = - phi2**2 * p1**2 * p2**2 - phi2**2 * p2**2 * d12**2 * b**2 - phi2**2 * p2**2 * d12**2 + phi2**2 * p2**4 + phi1**2 * p2 **4 + 2 * p1 * p2**2 * d12 + 2 * phi1 * phi2 * p1 * p2**2 * d12 * b - phi1**2 * p1**2 * p2**2 + 2 * phi2**2 * p1 * p2**2 * d12 - p2**2 * d12**2 * b**2 - 2 * p1**2 * p2**2
a1 = 2 * p1**2 * p2 * d12 * b + 2 * phi1 * phi2 * p2**3 * d12 - 2 * phi2**2 * p2**3 * d12 * b - 2 * p1 * p2 * d12**2 * b
a0 = - 2 * phi1 * phi2 * p1 * p2**2 * d12 * b + phi2**2 * p2**2 * d12**2 + 2 * p1**3 * d12 - p1**2 * d12**2 + phi2**2 * p1**2 * p2**2 - p1**4 - 2 * phi2**2 * p1 * p2**2 * d12 + phi1**2 * p1**2 * p2**2 + phi2**2 * p2**2 * d12**2 * b**2

print("a4 = ", a4)
print(a4.shape)  # (batch_size,1)
print("a3 = ", a3)
print("a3.shape = ", a3.shape)  # (batch_size,1)
print("a2 = ", a2)
print(a2.shape)  # (batch_size,1)
print("a1 = ", a1)
print(a1.shape)  # (batch_size,1)
print("a0 = ", a0)
print(a0.shape)  # (batch_size,1)


a4 =  tensor([[  -81.2098],
        [-1101.3248],
        [ -122.3042],
        [  -57.8566],
        [ -620.2046]], dtype=torch.float64)
torch.Size([5, 1])
a3 =  tensor([[ 5.0427e+01],
        [ 5.0530e+02],
        [-3.8267e+01],
        [ 3.5884e-01],
        [ 2.7286e+02]], dtype=torch.float64)
a3.shape =  torch.Size([5, 1])
a2 =  tensor([[-32.4642],
        [349.8376],
        [-82.7116],
        [ -1.4961],
        [265.1269]], dtype=torch.float64)
torch.Size([5, 1])
a1 =  tensor([[-34.8795],
        [-33.0958],
        [ 59.4238],
        [ -5.4821],
        [ 44.4879]], dtype=torch.float64)
torch.Size([5, 1])
a0 =  tensor([[ 46.6727],
        [ 58.5582],
        [151.9332],
        [  0.9051],
        [  8.6762]], dtype=torch.float64)
torch.Size([5, 1])


9. Recovery of the polynomial roots cos (teta)

In [ ]:
from torch import vmap

# Computation of the roots
roots = vmap(polynomial_root_calculation_4th_degree_ferrari)(torch.cat([a0,a1,a2,a3,a4],dim=1)) # (batch_size,4)

print("roots = \n", roots)  # list of tensor (for complex numbers)


j_batch = 
 tensor([[-0.5000,  0.8660],
        [-0.5000,  0.8660],
        [-0.5000,  0.8660]])
sqrt called with a =  BatchedTensor(lvl=1, bdim=0, value=
    tensor([2.3864e-02, 6.5140e-05, 3.2583e-01, 2.1274e-06, 3.4658e-06],
           dtype=torch.float64)
)
real_part =  BatchedTensor(lvl=1, bdim=0, value=
    tensor([0.1545, 0.0081, 0.5708, 0.0015, 0.0019], dtype=torch.float64)
)
imag_part =  BatchedTensor(lvl=1, bdim=0, value=
    tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
)
stacked result =  BatchedTensor(lvl=1, bdim=0, value=
    tensor([[0.1545, 0.0000],
            [0.0081, 0.0000],
            [0.5708, 0.0000],
            [0.0015, 0.0000],
            [0.0019, 0.0000]], dtype=torch.float64)
)
complex_number_power_k called with a =  BatchedTensor(lvl=2, bdim=0, value=
    tensor([[-0.5000,  0.8660],
            [-0.5000,  0.8660],
            [-0.5000,  0.8660]])
)  and k =  BatchedTensor(lvl=2, bdim=0, value=
    tensor([0, 1, 2])
)


RuntimeError: vmap: It looks like you're attempting to use a Tensor in some data-dependent control flow. We don't support that yet, please shout over at https://github.com/pytorch/functorch/issues/257 .

10. For each solution : computation of the camera position and rotation matrix

In [ ]:
# For each solution of the polynomial
for i in range(4):
  #if np.isclose(np.imag(roots[i]),0) : # if real solution 

    # Computation of trigonometrics forms
    cos_teta = torch.tensor(roots[i][0])# real part of the root 
    sin_teta = torch.sqrt(1-cos_teta**2)

    cot_alpha = ((phi1/phi2)*p1 + cos_teta*p2 -d12*b )/ ((phi1/phi2)*cos_teta* p2 - p1 + d12)

    sin_alpha = torch.sqrt(1/(cot_alpha**2+1))
    cos_alpha= torch.sqrt(1-sin_alpha**2)

    if cot_alpha < 0 :
      cos_alpha = -cos_alpha

    # Computation of the intermediate rotation's matrixs
    C_estimate = torch.tensor([d12*cos_alpha*(sin_alpha*b + cos_alpha), d12*sin_alpha*cos_teta*(sin_alpha*b+cos_alpha), d12*sin_alpha*sin_teta*(sin_alpha*b+cos_alpha)]) # (3,)
    print("C_estimate = \n", C_estimate)
    print(C_estimate.shape)  # (3,)
    Q = torch.tensor([[-cos_alpha, -sin_alpha*cos_teta, -sin_alpha*sin_teta], [sin_alpha, -cos_alpha*cos_teta, -cos_alpha*sin_teta], [0, -sin_teta, cos_teta]])    # (3*3)
    print("Q = \n", Q)
    print(Q.shape)  # (3,3)
    # Computation of the absolute camera center
  
    C_estimate = P1 + torch.tensordot(torch.transpose(N, 0,1), C_estimate, dims=1) # (3,)
    print("C_estimate = \n", C_estimate) 
    print(C_estimate.shape)  # (3,)
    C_estimate = torch.reshape(C_estimate, (3,1))  # Reshape to (3,1) for consistency
    print("C_estimate = \n", C_estimate)  # (3,1)
    print("C_estimate.shape = ", C_estimate.shape)  # (3,1)

    # Computation of the orientation matrix
    R_estimate = torch.tensordot(torch.tensordot(torch.transpose(N,0,1),torch.transpose(Q, 0,1), dims=1),T,dims=1)   # (3*3)
    print("R_estimate = \n", R_estimate)
    print(R_estimate.shape)  # (3,3)
    
    # Adding C and R to the solutions
    solutions[i,:,:1]= C_estimate
    solutions[i,:,1:] = R_estimate

print("solutions = \n", solutions)


In [ ]:
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

11. Reprojection of points in 2D from the newly estimated matrices to verify the estimation error.

In [ ]:
def projection3D2D(point3D,C,R,A) :
  # 3D point = [ Xw, Yw, Zw ]'   (1*3)
  # T : camera translation matrix : (3*1)
  # R : camera rotation matrix : (3*3)
  # A : intraseca matrix of the camera : (3*3)
  # Output : return the coordonates of the point in 2D 

  PI = torch.cat((torch.eye(3, dtype=torch.float64),torch.zeros((3,1), dtype=torch.float64)),dim=1)  # (3*4)

  Rt = torch.cat((R,C),dim=1)               # (3*4)
  Rt = torch.cat((Rt,torch.tensor([[0,0,0,1]], dtype=torch.float64)),dim=0)   # (4*4)

  point3D_bis = torch.cat((torch.reshape(point3D,(3,1)),torch.tensor([[1]],dtype=torch.float64)),dim=0)   #(4*1)
  
  point2D = torch.tensordot(torch.tensordot(torch.tensordot(A,PI,dims=1),Rt,dims=1),point3D_bis,dims=1)  # 2D point = [u, v, w] (3*1)
  point2D = point2D / point2D[2]        # 2D point = [u, v, 1] (3*1)
  return point2D[:2]


C_transpose = torch.transpose(C, 0, 1)  # (3*1) -> (1*3)

p1 = projection3D2D(P1,C_transpose,R,A)
print("p1 = ", p1)
print(p1.shape)  # (2,1)
p2 = projection3D2D(points3D[1],C_transpose,R,A)
print("p2 = ", p2)
p3 = projection3D2D(points3D[2],C_transpose,R,A)
print("p3 = ", p3)
p4 = projection3D2D(P4,C_transpose,R,A)
print("p4 = ", p4)




12. Calculation of errors = distance between the 2D points estimated from the found rotation and position matrices and the 2D points from the initial matrices

In [ ]:
def distance(pt, pt_estimation):
    erreur = torch.tensor(0, dtype=torch.float64)  # Initialize error as a tensor
    for i in range(len(pt)): 
      erreur = erreur + torch.tensor((pt[i] - pt_estimation[i])**2, dtype=torch.float64)  # Ensure each term is a tensor
      #erreur += (pt[i] - pt_estimation[i])**2
    return torch.sqrt(erreur)



def affichage_erreur(solutions,points2D,points3D,A) : 
   # Compute the error of estimation for each points after the P3P algorithm 

   # solutions : solution matrix returned by P3P (4*3*4)
   # points 3D : 4 pts 3D used for P3P 
   # points 2D : 4 pts 2D used for P3P (image of the 3D points)
   
   P1 = points3D[0]
   P2 = points3D[1]
   P3 = points3D[2]
   P4 = points3D[3]

   erreurs = []
   nb_sol = 0

   for i in range(len(solutions)) : 
      R = solutions[i,:,1:] 
      C = solutions[i,:,:1]

      if not torch.all(R==torch.zeros((3,3))) : 
        nb_sol += 1 
        print("------------ Solution n° : ",nb_sol,"----------------")
        print("R = \n",R,)
        print("T = \n",C,)

        p1_P3P = torch.reshape(projection3D2D(P1,C,R,A),(1,2))
        p2_P3P = torch.reshape(projection3D2D(P2,C,R,A),(1,2))
        p3_P3P = torch.reshape(projection3D2D(P3,C,R,A),(1,2))
        p4_P3P = torch.reshape(projection3D2D(P4,C,R,A),(1,2))
        pt_2D_P3P = torch.cat((p1_P3P,p2_P3P,p3_P3P,p4_P3P),dim=0)    # (4,2)

        erreurs.append([0])
        for j in range(len(points2D)):
            erreur_pt = distance(points2D[j],pt_2D_P3P[j])
            erreurs[i]+=erreur_pt
        
   indice_min = 0
   min = erreurs[0]
   for i in range(1,len(erreurs)) :
    if erreurs[i]<min :
      min = erreurs[i]
      indice_min = i

   R_opti = solutions[indice_min,:,1:] 
   C_opti = solutions[indice_min,:,:1]
   print("\n------------ Best solution : ----------------")
   print("Solution n° :",indice_min+1,"\n")
   print("R estimé = \n", R_opti,"\n")
   print("T estimé = \n", C_opti, "\n")

In [ ]:
affichage_erreur(solutions, [p1, p2, p3, p4], [P1,P2,P3, P4], A)