In [19]:
import numpy as np 
import torch

batch_size = 5 

At first we have : 
- camera's parameters -> A (focal, center) 
- rotation matrix  -> R 
- position matrix -> C 
- 3D points position ->  P1 P2 P3 (and P4 to determinate the best solution after P3P)

In [20]:
# This script defines the camera parameters, rotation matrix, and translation matrix.
def camera() : 
  # Definition of the camera parameters
  # focal length
  fx = 800
  fy = 800
  # center
  cx = 320 
  cy = 240

  A = torch.tensor([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=torch.float64) # intraseca matrix of the camera (3*3)
  #A = torch.from_numpy(A)  # Convert to a PyTorch tensor
  print("A = \n", A)
  print(A.shape)  # (3*3)
  A_batch = A.repeat(batch_size,1,1)
  print("A_batch = \n", A_batch)
  print(A_batch.shape)  # (batch_size, 3, 3)
  return A_batch

A = camera() 



def rotation_matrix() : 
  # Definition of the rotation matrix of the camera 
  R = torch.tensor([[1, 0, 0],[0, -1, 0], [0, 0, -1]], dtype=torch.float64)  # (3*3)
  #R = torch.from_numpy(R)  # Convert to a PyTorch tensor
  print("R = \n",R)
  print(R.shape)  # (3*3)
  R_batch = R.repeat(batch_size,1,1)  # Repeat the rotation matrix for each batch
  print("R_batch = \n", R_batch)  
  print(R_batch.shape)  # (batch_size, 3, 3)
  return R_batch

def camera_position() : 
  # Definition of the translation matrix of the camera (the position)
  C = torch.tensor([[0,0,6]], dtype=torch.float64)    # T = [tx,ty,tz]  (1*3)
  print("C = \n",C)
  print(C.shape)  # (1*3)

  C_batch = C.repeat(batch_size, 1)  # Repeat the translation vector for each batch
  print("C_batch = \n", C_batch)  
  print(C_batch.shape)  # (batch_size, 3)

 
  return C_batch

R = rotation_matrix()
C = camera_position()

A = 
 tensor([[800.,   0., 320.],
        [  0., 800., 240.],
        [  0.,   0.,   1.]], dtype=torch.float64)
torch.Size([3, 3])
A_batch = 
 tensor([[[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]]], dtype=torch.float64)
torch.Size([5, 3, 3])
R = 
 tensor([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]], dtype=torch.float64)
torch.Size([3, 3])
R_batch = 
 tensor([[[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.

In [21]:
# Definition of 3D points in the world coordinate system
def point3Daleatoire(x) :
  # Generation of one random points in 3D space 
  return torch.tensor([[np.random.uniform(-x,x),np.random.uniform(-x,x),np.random.uniform(-x,x)]])

def pts_3D_4pts():
  # Generate randomly 4 3D points
  # Output : tensor which concatenate the 4 points = [ P1, P2, P3, P4 ] 

  P1 = point3Daleatoire(2)     # (1*3) -> pour P3P
  P2 = point3Daleatoire(2)
  P3 = point3Daleatoire(2)
  P4 = point3Daleatoire(2)
  
  points3D = torch.cat((P1,P2,P3,P4),dim=0);     # (LIGNES 4* COLONNES 3) - xyz
  print("points3D = \n", points3D)
  print(points3D.shape)  # (4*3)

  
  return points3D

def pts_3D_4pts_batch():
  # Generate randomly 4 3D points for each batch
  # Output : array which concatenate the 4 points = [ P1, P2, P3, P4 ] for each batch

  # Generate a batch of random points in 3D space
  # Each point is generated independently for each batch

  points3D_batch = torch.stack([pts_3D_4pts() for i in range(batch_size)])  # (batch_size, 4, 3)
  print("points3D_batch = \n", points3D_batch)
  print(points3D_batch.shape)  # (batch_size, 4, 3)
  return points3D_batch

points3D_batch = pts_3D_4pts_batch()  # Generate the batch of 3D points
'''
P1 = torch.tensor([0.7161, 0.5431, 1.7807], dtype=torch.float64)    # (3,)
P2 = torch.tensor([-1.1643, 0.8371, -1.0551], dtype=torch.float64)
P3 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64)
P4 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64) 
'''
P1 = points3D_batch[:, 0, :]  # Extract P1 for each batch
P2 = points3D_batch[:, 1, :]  # Extract P2 for each batch
P3 = points3D_batch[:, 2, :]  # Extract P3 for each batch
P4 = points3D_batch[:, 3, :]  # Extract P4 for each batch

print("P1 = \n", P1)
print(P1.shape)  # (batch_size, 3)
print("batch_size = ", batch_size)


points3D = 
 tensor([[-0.6899,  0.6549,  0.7881],
        [ 1.8524,  0.2984, -1.7253],
        [ 1.5534,  1.9822, -0.4189],
        [ 0.8304, -1.3522, -0.3058]])
torch.Size([4, 3])
points3D = 
 tensor([[-0.8011, -1.5585, -1.9665],
        [-1.6682,  1.7854, -1.1978],
        [ 0.4548, -1.4646, -1.1198],
        [ 1.2415,  1.6058,  0.2640]])
torch.Size([4, 3])
points3D = 
 tensor([[-0.0313, -1.1730, -1.6763],
        [-1.9472,  1.1870,  1.2191],
        [-0.5641,  0.4636,  1.6231],
        [-0.6476, -1.0415,  0.5870]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.7288,  0.0142, -1.0926],
        [ 1.0677,  1.3174,  1.5078],
        [-1.8876,  1.8588,  0.1510],
        [-1.2002,  1.8828,  0.5903]])
torch.Size([4, 3])
points3D = 
 tensor([[ 0.2017, -1.5929,  1.7698],
        [-0.2667, -1.9715, -0.5921],
        [-0.4518,  0.2330,  1.1972],
        [ 0.9084, -0.4088, -1.0163]])
torch.Size([4, 3])
points3D_batch = 
 tensor([[[-0.6899,  0.6549,  0.7881],
         [ 1.8524,  0.2984, -1.7253],


We create the 3 direction features vectors f1, f2, f3

In [22]:
def features_vectors(points3D,C, R,batch_size) :
    '''
    This function computes the features vectors for P3P algorithm.
    args:
    points3D : array with the 4 3D points = [ P1, P2, P3, P4 ] (4*3) 
    but we only use the first three points for P3P
    C: camera position matrix : (3*1)
    returns:
    featuresVect : array with the features vectors (9*1)
    '''
    P1 = torch.reshape(points3D[0], (batch_size,3,1))  # Reshape to (3,1) for easier calculations
    print("P1 = \n", P1)  # Print P1 to check the values
    print(P1.shape)  # (batch_size, 3, 1)
    P2 = torch.reshape(points3D[1], (batch_size,3,1))
    P3 = torch.reshape(points3D[2], (batch_size,3,1))

    C = torch.reshape(C, (batch_size,3,1))  # Reshape C to (3,1) for easier calculations
    print("C = \n", C)  # Print C to check the values
    print(C.shape)  # (batch_size, 3, 1)

    v1 = torch.matmul(R,(P1 - C))  # Calculate the vector from camera to P1
    print("v1 = \n", v1)  # Print v1 to check the values
    print(v1.shape)  # (batch_size, 3, 1)
    v2 = torch.matmul(R,(P2 - C))  # Calculate the vector from camera to P2
    v3 = torch.matmul(R,(P3 - C))  # Calculate the vector from camera to P3

    f1 = v1 / torch.norm(v1,dim=1, keepdim=True)  # Normalize the vector v1
    f2 = v2 / torch.norm(v2,dim=1, keepdim=True)  # Normalize the vector v2
    f3 = v3 / torch.norm(v3,dim=1, keepdim=True)  # Normalize the vector v3

    print("f1 = \n", f1)  # Print f1 to check the values
    print(f1.shape)  # (batch_size, 3, 1)

    f1 = torch.reshape(f1, (batch_size,1,3))  # Reshape to (3,1)
    print("f1 : ",f1.shape) # (batch_size,1,3)
    f2 = torch.reshape(f2, (batch_size,1,3))
    f3 = torch.reshape(f3, (batch_size,1,3))

    featuresVect = torch.cat((f1,f2,f3),dim=1)
    print("features vectors = \n",featuresVect)
    print(featuresVect.shape)  # (batch_size, 3, 3)

    return featuresVect # Return the features vectors need in P3P


points3D = [P1, P2, P3]  # We define the points3D with the first three points
print("points3D = \n", points3D)  # Print the points3D to check the values  / List len = 3 

print("batch_size = ", batch_size)
featuresVect = features_vectors(points3D, C, R,batch_size)  

points3D = 
 [tensor([[-0.6899,  0.6549,  0.7881],
        [-0.8011, -1.5585, -1.9665],
        [-0.0313, -1.1730, -1.6763],
        [-1.7288,  0.0142, -1.0926],
        [ 0.2017, -1.5929,  1.7698]]), tensor([[ 1.8524,  0.2984, -1.7253],
        [-1.6682,  1.7854, -1.1978],
        [-1.9472,  1.1870,  1.2191],
        [ 1.0677,  1.3174,  1.5078],
        [-0.2667, -1.9715, -0.5921]]), tensor([[ 1.5534,  1.9822, -0.4189],
        [ 0.4548, -1.4646, -1.1198],
        [-0.5641,  0.4636,  1.6231],
        [-1.8876,  1.8588,  0.1510],
        [-0.4518,  0.2330,  1.1972]])]
batch_size =  5
P1 = 
 tensor([[[-0.6899],
         [ 0.6549],
         [ 0.7881]],

        [[-0.8011],
         [-1.5585],
         [-1.9665]],

        [[-0.0313],
         [-1.1730],
         [-1.6763]],

        [[-1.7288],
         [ 0.0142],
         [-1.0926]],

        [[ 0.2017],
         [-1.5929],
         [ 1.7698]]])
torch.Size([5, 3, 1])
C = 
 tensor([[[0.],
         [0.],
         [6.]],

        [[0.],
  

Lastly we need the functions to resolve the polynomial roots. - for test go to test resolution polynome 

In [23]:
from complex_batch_utils import *
import complex_utils as cpu
from torch import vmap

def polynomial_root_calculation_3rd_degree(a, b, c, d):
    # This function calculates the roots of a cubic polynomial of the form:
    # a*x^3 + b*x^2 + c*x + d = 0
        # a (batch_size, 1)
        # b (batch_size, 1)
        # c (batch_size, 1)
        # d (batch_size, 1)

    # output: roots of the polynomial in the form of a tensor of shape (batch_size,3, 2)
    # where each root is represented as a complex number (real, imaginary)
    # each row is the i_th root of the polynomial
    
    batch_size = a.shape[0]  # Get the batch size from the shape of a
    

    # Discriminant terms
    p = (3 * a * c - b**2) / (3 * a**2)     # (batch_size, 1) because element-wise opeations
    q = (2 * b**3 - 9 * a * b * c + 27 * a**2 * d) / (27 * a**3)    # (batch_size, 1)
    delta = -4 * p**3 - 27 * q**2   # (batch_size, 1)

    roots = torch.empty((batch_size,3, 2))  # Initialize roots tensor to store the roots

    j_ = torch.tensor([-0.5, torch.sqrt(torch.tensor(3))/2])  # cube root of unity
    
    for k in range (3):
        delta_sur_27 = -delta / 27   #(batch_size, 1) 

        sqrt_term = sqrt_batch(delta_sur_27)  

        # faire une seule fois les calculs de j^k et j^-k
        j_exp_k = cpu.complex_number_power_k(j_, k)  # Compute j^k for each batch
        j_exp_moins_k = cpu.complex_number_power_k(j_, -k)  # Compute j^-k for each batch

        j_exp_k_batch = j_exp_k.repeat(batch_size, 1)
        j_exp_moins_k_batch = j_exp_moins_k.repeat(batch_size, 1)

        u_k = product_of_2_complex_numbers_batch(j_exp_k_batch, sqrt_3_batch(torch.stack([0.5*(-q.squeeze()+sqrt_term[:,0]),sqrt_term[:,1]],dim=-1)) )
         # (batch_size, 2) 
        v_k = product_of_2_complex_numbers_batch(j_exp_moins_k_batch, sqrt_3_batch(torch.stack([0.5*(-q.squeeze()-sqrt_term[:,0]),-0.5*sqrt_term[:,1]],dim=-1)))
          # (batch_size, 2) 

        root = addition_batch(addition_batch(u_k, v_k), torch.stack([-b[:,0]/(3*a[:,0]),0.0*b[:,0]],dim=-1) ) 
         # (batch_size, 2)

        roots[:,k,:] = root  # Store the root in the roots tensor

    return roots


In [24]:

def polynomial_root_calculation_4th_degree_ferrari(a0, a1, a2, a3, a4): # Ferrari's Method
    print("a0 = \n", a0)  # Print a0 to check the values
    print(a0.shape)  # (batch_size, 1)

    
    # Solving a polynomial of 4th degree
    # a0, a1, a2, a3, a4 (batch_size,1)

    # Output : roots of the polynomial a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0   (4,batch_size 2) !! ATTENTION !!! 

    batch_size = a0.shape[0]  # Get the batch size from the shape of a0

    # Reduce the quartic equation to the form : x^4 + a*x^3 + b*x^2 + c*x + d = 0
    a = a3/a4           # (batch_size, 1)
    print("a",a.shape)  # (batch_size, 1)
    b = a2/a4
    c = a1/a4
    d = a0/a4

    # Computation of the coefficients of the Ferrari's Method
    S = a/4     # (batch_size, 1)
    b0 = d - c*S + b* S**2 - 3* S**4    # (batch_size, 1)
    b1 = c - 2*b*S + 8*S**3 # (batch_size, 1)
    b2 = b - 6 * S**2  # (batch_size, 1)


    # Solve the cubic equation m^3 + b2*m^2 + (b2^2/4  - b0)*m - b1^2/8 = 0
    x_cube = polynomial_root_calculation_3rd_degree(torch.tensor(1).repeat(b2.shape),b2,(b2**2)/4-b0,(-b1**2)/8)
    print("x_cube ", x_cube)  # Print the roots of the cubic equation
    print(x_cube.shape)
    

    x_cube_real = x_cube[:,:,0]  # Extract the real part of the roots  (batch_size, 3)
    print("x_cube_real = \n", x_cube_real)  
    print(x_cube_real.shape)  

    x_cube_imag = x_cube[:,:,1]  # Extract the imaginary part of the roots    (batch_size, 3)

    is_real = torch.isclose(x_cube_imag,torch.tensor(0.0))
    is_positive = x_cube[:,:,0] > 0
    condition = is_real & is_positive  # Condition to check if the root is real and positive   (batch_size, 3)
   
    
    real_filtered = x_cube_real.clone()
    real_filtered[~condition] = float('inf')  # if root real and positive, keep it, else set to infinity   (batch_size, 3)


    alpha_0_real, _ = real_filtered.min(dim=1) # Get the minimum real part of the roots (if doesn't exist, returns inf)

    alpha_0 = torch.stack([alpha_0_real, torch.zeros(batch_size)], dim=-1)  # (batch_size,2)
    

    # do the calculation for alpha_0_nul and not alpha_0_nul and then affects the good value 

    # if alpha_0_nul == False
    alpha0_div_2 = 0.5*alpha_0              # beacause alpha_0 is real  # (batch_size, 2)    
    sqrt_alpha = sqrt_batch(alpha0_div_2[:,0].unsqueeze(-1))    # input : (batch_size, 1) // output : (batch_size, 2)
    term = addition_complex_real_batch(- alpha0_div_2 ,-b2 / 2)      # (batch_size, 2)
    denom = 2 * torch.sqrt(2 * alpha_0)      # beacause alpha_0 is real  # (batch_size, 2)
    num = torch.stack([b1, torch.zeros(batch_size,1)], dim=-1).squeeze(1)  # (batch_size, 2)
   

    frac = division_2_complex_numbers(num,denom)    # (batch_size, 2)
    print("frac = \n", frac)  # Print the fraction to check the values
    print(frac.shape)  # (batch_size, 2)

    x1_false = addition_complex_real_batch(sqrt_alpha ,- S) + sqrt_complex_batch(addition_batch(term,-frac))    # (batch_size, 2)
    x2_false = addition_complex_real_batch(sqrt_alpha, - S) - sqrt_complex_batch(addition_batch(term,-frac))    # (batch_size, 2)
    x3_false = addition_complex_real_batch(-sqrt_alpha, - S) + sqrt_complex_batch(addition_batch(term,frac))    # (batch_size, 2)
    x4_false = addition_complex_real_batch(-sqrt_alpha,- S) - sqrt_complex_batch(addition_batch(term,frac))     # (batch_size, 2)
    
    # if alpha_0_nul == True
    print("b2 ", b2.shape)  # (batch_size, 1)
    print((b2**2) / 4 - b0)
    sqrt_inner1 = sqrt_batch((b2**2) / 4 - b0)        # complex 

    x1_true = addition_complex_real_batch(sqrt_complex_batch(addition_complex_real_batch(sqrt_inner1,-b2 / 2)),-S)
    x2_true = addition_complex_real_batch(- sqrt_complex_batch(addition_complex_real_batch(sqrt_inner1,-b2 / 2)),-S)
    x3_true = addition_complex_real_batch(sqrt_complex_batch(addition_complex_real_batch(- sqrt_inner1,-b2 / 2 )),-S)
    x4_true = addition_complex_real_batch(- sqrt_complex_batch(addition_complex_real_batch(- sqrt_inner1,-b2 / 2 )),-S)
    
    result = torch.where(alpha_0==float('inf'),
                         torch.stack([x1_true, x2_true, x3_true, x4_true]),torch.stack([x1_false, x2_false, x3_false, x4_false]))
    print("result = \n", result.shape)  # Print the result to check the values
    return result   # (4,batch_size, 2)

print("batch_size = ", batch_size) 
a0  = torch.rand(batch_size, 1, dtype=torch.float64)
a1  = torch.rand(batch_size, 1, dtype=torch.float64)  
a2  = torch.rand(batch_size, 1, dtype=torch.float64)  
a3  = torch.rand(batch_size, 1, dtype=torch.float64) 
a4  = torch.rand(batch_size, 1, dtype=torch.float64)  
print(polynomial_root_calculation_4th_degree_ferrari(a0, a1, a2, a3, a4))  # Call the function to calculate the roots of the polynomial


batch_size =  5
a0 = 
 tensor([[0.0367],
        [0.2875],
        [0.8106],
        [0.7729],
        [0.0226]], dtype=torch.float64)
torch.Size([5, 1])
a torch.Size([5, 1])
x_cube  tensor([[[ 0.0500,  0.0000],
         [-1.1574,  0.0000],
         [-1.1574,  0.0000]],

        [[ 2.6066,  0.0000],
         [ 0.5620,  0.9174],
         [ 0.5620, -0.9174]],

        [[-1.1282,  0.0000],
         [ 0.2800,  0.0000],
         [ 0.2800,  0.0000]],

        [[-0.6140,  0.0000],
         [ 0.1948,  0.0000],
         [ 0.1948,  0.0000]],

        [[ 0.0591,  0.0000],
         [-0.0545,  0.0000],
         [-0.0545,  0.0000]]])
torch.Size([5, 3, 2])
x_cube_real = 
 tensor([[ 0.0500, -1.1574, -1.1574],
        [ 2.6066,  0.5620,  0.5620],
        [-1.1282,  0.2800,  0.2800],
        [-0.6140,  0.1948,  0.1948],
        [ 0.0591, -0.0545, -0.0545]])
torch.Size([5, 3])
a.shape =  torch.Size([5, 2])
b.shape =  torch.Size([5, 1])
frac = 
 tensor([[1.3199, 0.0000],
        [1.0759, 0.0000],
        

We have all the variables needed for the p3p so we start

1. Storage of points : already done 

In [25]:
print("P1 = \n", P1)
print("batch_size = ", batch_size)
print("P2 = \n", P2)
print("P3 = \n", P3)

P1 = 
 tensor([[-0.6899,  0.6549,  0.7881],
        [-0.8011, -1.5585, -1.9665],
        [-0.0313, -1.1730, -1.6763],
        [-1.7288,  0.0142, -1.0926],
        [ 0.2017, -1.5929,  1.7698]])
batch_size =  5
P2 = 
 tensor([[ 1.8524,  0.2984, -1.7253],
        [-1.6682,  1.7854, -1.1978],
        [-1.9472,  1.1870,  1.2191],
        [ 1.0677,  1.3174,  1.5078],
        [-0.2667, -1.9715, -0.5921]])
P3 = 
 tensor([[ 1.5534,  1.9822, -0.4189],
        [ 0.4548, -1.4646, -1.1198],
        [-0.5641,  0.4636,  1.6231],
        [-1.8876,  1.8588,  0.1510],
        [-0.4518,  0.2330,  1.1972]])


2. Storage of the features vectors : done

In [26]:
# we got featuresVect and we access the 3 values 
f1 = featuresVect[:,0,:]  # Access the first feature vector for each batch
f2 = featuresVect[:,1,:]
f3 = featuresVect[:,2,:]

print("f1 = ", f1)
print(f1.shape)  # (batsh_size,3)
print("f2 = ", f2)
print(f2.shape)  # (batsh_size,3)
print("f3 = ", f3)
print(f3.shape)  # (batsh_size,3)

f1 =  tensor([[-0.1302, -0.1236,  0.9837],
        [-0.0982,  0.1911,  0.9767],
        [-0.0040,  0.1510,  0.9885],
        [-0.2368, -0.0019,  0.9716],
        [ 0.0446,  0.3520,  0.9349]], dtype=torch.float64)
torch.Size([5, 3])
f2 =  tensor([[ 0.2330, -0.0375,  0.9718],
        [-0.2195, -0.2349,  0.9469],
        [-0.3676, -0.2241,  0.9026],
        [ 0.2224, -0.2744,  0.9356],
        [-0.0387,  0.2863,  0.9574]], dtype=torch.float64)
torch.Size([5, 3])
f3 =  tensor([[ 0.2253, -0.2875,  0.9309],
        [ 0.0624,  0.2011,  0.9776],
        [-0.1271, -0.1045,  0.9864],
        [-0.2940, -0.2895,  0.9109],
        [-0.0935, -0.0482,  0.9944]], dtype=torch.float64)
torch.Size([5, 3])


3. Création of a solution variable : maximum 4 solutions  

    Matrix (4,3,4)  
    Each layer is a solution, for each leayer : first column stres the camera position matrix C (3,1) and the remaining 3 columns store the rotation matrix R (3,3)

In [27]:
solutions = torch.zeros((batch_size,4,3,4), dtype=torch.float64)
print("batch_size = ", batch_size)
print("solutions = \n", solutions)
print(solutions.shape)  # (batch_size,4,3,4)

batch_size =  5
solutions = 
 tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0

4. Verification that the 3 points given are not collinear 

In [28]:
# Test of non-collinearity
print("P1 = \n", P1)
print(P1.shape)  # (batch_size, 3)

v1 = P2 - P1
print("v1 = \n", v1)  # Print v1 to check the values
print(v1.shape)  # (batch_size, 3)
v2 = P3 - P1

norms = torch.norm(torch.cross(v1,v2, dim=1),dim = 1 )
print("norms : ",norms.shape)  # (batch_size,)

all_dif_zero = torch.all(norms != 0)  # Check if all norms are non-zero

if not all_dif_zero:
    print('\nProblem: the points must not be collinear')
else:
    print('\nThe points are not collinear, we can continue')

P1 = 
 tensor([[-0.6899,  0.6549,  0.7881],
        [-0.8011, -1.5585, -1.9665],
        [-0.0313, -1.1730, -1.6763],
        [-1.7288,  0.0142, -1.0926],
        [ 0.2017, -1.5929,  1.7698]])
torch.Size([5, 3])
v1 = 
 tensor([[ 2.5423, -0.3565, -2.5134],
        [-0.8671,  3.3438,  0.7687],
        [-1.9159,  2.3600,  2.8954],
        [ 2.7965,  1.3032,  2.6004],
        [-0.4684, -0.3786, -2.3618]])
torch.Size([5, 3])
norms :  torch.Size([5])

The points are not collinear, we can continue


5. Creation of an orthonormal frame from f1, f2, f3 (the features vectors)

In [29]:
# Calculation of vectors of the base τ = (C,tx,ty,tz)
tx = f1     
print("tx = ", tx)
print(tx.shape)  # (batch_size,3)

tz = torch.cross(f1,f2,dim=1)/ torch.norm(torch.cross(f1,f2,dim=1),dim=1, keepdim=True)  # Normalize the cross product to get tz
print("tz = ", tz)
print(tz.shape)  # (batch_size,3)

ty = torch.cross(tz,tx,dim=1)
print("ty = ", ty)
print(ty.shape)  # (batch_size,3)

tx =  tensor([[-0.1302, -0.1236,  0.9837],
        [-0.0982,  0.1911,  0.9767],
        [-0.0040,  0.1510,  0.9885],
        [-0.2368, -0.0019,  0.9716],
        [ 0.0446,  0.3520,  0.9349]], dtype=torch.float64)
torch.Size([5, 3])
tz =  tensor([[-0.2267,  0.9696,  0.0918],
        [ 0.9481, -0.2804,  0.1502],
        [ 0.7009, -0.7046,  0.1105],
        [ 0.5135,  0.8487,  0.1269],
        [ 0.6403, -0.7285,  0.2438]], dtype=torch.float64)
torch.Size([5, 3])
ty =  tensor([[ 0.9652,  0.2111,  0.1543],
        [-0.3025, -0.9407,  0.1536],
        [-0.7132, -0.6933,  0.1030],
        [ 0.8248, -0.5289,  0.2000],
        [-0.7669, -0.5877,  0.2579]], dtype=torch.float64)
torch.Size([5, 3])


5. (bis) Creation of a transformation matrix T and expression of the f3 vector in this frame

In [30]:
print("tx = \n", tx)
print(tx.shape)  # (batch_size,3)
print("batch_size = ", batch_size)

tx = torch.reshape(tx,(batch_size,1,3))   # (batch_sizee,1,3)
print("tx = \n", tx)
print(tx.shape)  # (batch_size,1,3)

ty = torch.reshape(ty,(batch_size,1,3))
print("ty = \n", ty)
print(ty.shape)  # (batch_size,1,3)

tz = torch.reshape(tz,(batch_size,1,3))
print("tz = \n", tz)
print(tz.shape)  # (batch_size,1,3)

# Computation of the matrix T and the feature vector f3
T = torch.cat((tx,ty,tz),dim = 1) # (3*3)
print("T = \n", T)
print(T.shape)  # (batch_size,3,3)


f3_T = torch.matmul(T,f3.unsqueeze(-1)) # (
print("f3_T = \n", f3_T)
print(f3_T.shape)  # (batch_size,3,1)


tx = 
 tensor([[-0.1302, -0.1236,  0.9837],
        [-0.0982,  0.1911,  0.9767],
        [-0.0040,  0.1510,  0.9885],
        [-0.2368, -0.0019,  0.9716],
        [ 0.0446,  0.3520,  0.9349]], dtype=torch.float64)
torch.Size([5, 3])
batch_size =  5
tx = 
 tensor([[[-0.1302, -0.1236,  0.9837]],

        [[-0.0982,  0.1911,  0.9767]],

        [[-0.0040,  0.1510,  0.9885]],

        [[-0.2368, -0.0019,  0.9716]],

        [[ 0.0446,  0.3520,  0.9349]]], dtype=torch.float64)
torch.Size([5, 1, 3])
ty = 
 tensor([[[ 0.9652,  0.2111,  0.1543]],

        [[-0.3025, -0.9407,  0.1536]],

        [[-0.7132, -0.6933,  0.1030]],

        [[ 0.8248, -0.5289,  0.2000]],

        [[-0.7669, -0.5877,  0.2579]]], dtype=torch.float64)
torch.Size([5, 1, 3])
tz = 
 tensor([[[-0.2267,  0.9696,  0.0918]],

        [[ 0.9481, -0.2804,  0.1502]],

        [[ 0.7009, -0.7046,  0.1105]],

        [[ 0.5135,  0.8487,  0.1269]],

        [[ 0.6403, -0.7285,  0.2438]]], dtype=torch.float64)
torch.Size([5, 1, 3])
T

The sing of the z-coordinate in f3_T give us the sign of teta, that we will need after 

In [31]:
print(f3_T[:,2])
f3_T_positif = f3_T[:,2] > 0

print("f3_T_positif = \n", f3_T_positif)
print(f3_T_positif.shape)  # (batch_size,1)

tensor([[-0.2443],
        [ 0.1496],
        [ 0.0935],
        [-0.2811],
        [ 0.2177]], dtype=torch.float64)
f3_T_positif = 
 tensor([[False],
        [ True],
        [ True],
        [False],
        [ True]])
torch.Size([5, 1])


6. Change of frame is performed on the 3D points side, and the transformation matrix N is defined

In [32]:
# Calculation of vectors of the base η = (P1,nx,ny,nz)
nx = (P2 - P1)/torch.norm(P2 - P1,dim=1,keepdim=True)      #(batch_size,3)
print("nx : ", nx.shape)  # (batch_size,3)

nz = torch.cross(nx,P3-P1,dim=1)/torch.norm(torch.cross(nx,P3-P1,dim=1), dim=1, keepdim=True) 
print("nz : ", nz.shape)  # (batch_size,3)

ny = torch.cross(nz,nx,dim=1)
print("ny : ", ny.shape)  # (batch_size,3)


# Reshape the vectors to (1,3) for concatenation
nx = torch.reshape(nx,(batch_size,1,3))  # (batch_size,1,3)
ny = torch.reshape(ny,(batch_size,1,3))
nz = torch.reshape(nz,(batch_size,1,3))

print("nx = \n", nx)
print(nx.shape)  # (1*3)
print("ny = \n", ny)
print("nz = \n", nz)

# Computation of the matrix N and the world point P3
N = torch.cat((nx,ny,nz),dim = 1) #  T's equivalent in the world coordinate system
print("N = \n", N)
print(N.shape)  # (batch_size,3,3)

print("P3.shape = ", P3.shape)  # (batch_size,3)

P3_n = torch.matmul(N,(P3-P1).unsqueeze(-1)) 


print("P3_n = \n", P3_n)
print(P3_n.shape)  # (5,3,1)


nx :  torch.Size([5, 3])
nz :  torch.Size([5, 3])
ny :  torch.Size([5, 3])
nx = 
 tensor([[[ 0.7076, -0.0992, -0.6996]],

        [[-0.2450,  0.9449,  0.2172]],

        [[-0.4564,  0.5622,  0.6897]],

        [[ 0.6931,  0.3230,  0.6445]],

        [[-0.1922, -0.1553, -0.9690]]])
torch.Size([5, 1, 3])
ny = 
 tensor([[[ 0.3578,  0.9041,  0.2337]],

        [[ 0.8221,  0.0837,  0.5631]],

        [[ 0.7288, -0.2085,  0.6522]],

        [[-0.5770,  0.7845,  0.2273]],

        [[-0.2911,  0.9520, -0.0949]]])
nz = 
 tensor([[[ 0.6093, -0.4157,  0.6752]],

        [[ 0.5139,  0.3166, -0.7973]],

        [[ 0.5105,  0.8003, -0.3145]],

        [[-0.4322, -0.5294,  0.7301]],

        [[ 0.9372,  0.2639, -0.2282]]])
N = 
 tensor([[[ 0.7076, -0.0992, -0.6996],
         [ 0.3578,  0.9041,  0.2337],
         [ 0.6093, -0.4157,  0.6752]],

        [[-0.2450,  0.9449,  0.2172],
         [ 0.8221,  0.0837,  0.5631],
         [ 0.5139,  0.3166, -0.7973]],

        [[-0.4564,  0.5622,  0.6897],
      

7. Definition of the variables for the following steps 

In [33]:
# Computation of phi1 et phi2 with 0=x, 1=y, 2=z
phi1 = f3_T[:,0]/f3_T[:,2]
phi2 = f3_T[:,1]/f3_T[:,2]
print("phi1 = ", phi1)
print(phi1.shape)  # (batch_size,1)
print("phi2 = ", phi2)
print(phi2.shape)  # (batch_size,1)

# Extraction of p1 and p2 from P3_eta
p1 = P3_n[:,0] #x
p2 = P3_n[:,1] #y
print("p1 = ", p1)
print(p1.shape)  # (batch_size,3)
print("p2 = ", p2)
print(p2.shape)  # (batch_size,3)

# Computation of d12
d12 = torch.norm(P2-P1,dim=1, keepdim=True) 
print("d12 = ", d12)
print(d12.shape)  # (batch_size,1)

# Computation of b = cot(beta)
cosBeta =( torch.sum(f1*f2,dim=1)/(torch.norm(f1,dim=1)*torch.norm(f2,dim=1)) ).unsqueeze(-1)  # tensor.dot(a,b) <=> tensor.sum(a*b)
print("cosBeta = ", cosBeta)  
print(cosBeta.shape)  # (batch_size,1)

b = torch.sqrt(1/(1-cosBeta**2)-1)
print("b = ", b)
print(b.shape)  # (batch_size,1)

b = torch.where(cosBeta < 0, -b, b)  # If cosBeta < 0, then b = -b
print("b = ", b)
print(b.shape)  # (batch_size,1)

phi1 =  tensor([[-3.7732],
        [ 6.5961],
        [10.2622],
        [-3.3983],
        [ 4.1741]], dtype=torch.float64)
torch.Size([5, 1])
phi2 =  tensor([[-1.2294],
        [-0.3869],
        [ 2.8306],
        [-0.3302],
        [ 1.6379]], dtype=torch.float64)
torch.Size([5, 1])
p1 =  tensor([[ 2.3001],
        [-0.0351],
        [ 3.4388],
        [ 1.2872],
        [ 0.3968]])
torch.Size([5, 1])
p2 =  tensor([[1.7206],
        [1.5172],
        [1.4223],
        [1.8214],
        [1.9827]])
torch.Size([5, 1])
d12 =  tensor([[3.5928],
        [3.5389],
        [4.1980],
        [4.0349],
        [2.4374]])
torch.Size([5, 1])
cosBeta =  tensor([[0.9303],
        [0.9015],
        [0.8598],
        [0.8568],
        [0.9941]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[2.5353],
        [2.0830],
        [1.6841],
        [1.6618],
        [9.1793]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[2.5353],
        [2.0830],
        [1.6841],
        [1.6618],
   

8. Calculation of the coefficients of the polynomial 

In [34]:
a4 = - phi2**2 * p2**4 - phi1**2 * p2**4 - p2**4
a3 = 2 * p2**3 * d12 * b + 2 * phi2**2 * p2**3 * d12 * b - 2 * phi1 * phi2 * p2**3 * d12
a2 = - phi2**2 * p1**2 * p2**2 - phi2**2 * p2**2 * d12**2 * b**2 - phi2**2 * p2**2 * d12**2 + phi2**2 * p2**4 + phi1**2 * p2 **4 + 2 * p1 * p2**2 * d12 + 2 * phi1 * phi2 * p1 * p2**2 * d12 * b - phi1**2 * p1**2 * p2**2 + 2 * phi2**2 * p1 * p2**2 * d12 - p2**2 * d12**2 * b**2 - 2 * p1**2 * p2**2
a1 = 2 * p1**2 * p2 * d12 * b + 2 * phi1 * phi2 * p2**3 * d12 - 2 * phi2**2 * p2**3 * d12 * b - 2 * p1 * p2 * d12**2 * b
a0 = - 2 * phi1 * phi2 * p1 * p2**2 * d12 * b + phi2**2 * p2**2 * d12**2 + 2 * p1**3 * d12 - p1**2 * d12**2 + phi2**2 * p1**2 * p2**2 - p1**4 - 2 * phi2**2 * p1 * p2**2 * d12 + phi1**2 * p1**2 * p2**2 + phi2**2 * p2**2 * d12**2 * b**2

print("a4 = ", a4)
print(a4.shape)  # (batch_size,1)
print("a3 = ", a3)
print("a3.shape = ", a3.shape)  # (batch_size,1)
print("a2 = ", a2)
print(a2.shape)  # (batch_size,1)
print("a1 = ", a1)
print(a1.shape)  # (batch_size,1)
print("a0 = ", a0)
print(a0.shape)  # (batch_size,1)


a4 =  tensor([[-146.8061],
        [-236.6375],
        [-467.8288],
        [-139.3095],
        [-326.1838]], dtype=torch.float64)
torch.Size([5, 1])
a3 =  tensor([[  63.2690],
        [ 122.2895],
        [-335.0565],
        [  35.1496],
        [1024.7185]], dtype=torch.float64)
a3.shape =  torch.Size([5, 1])
a2 =  tensor([[ -116.2658],
        [   85.4597],
        [ -108.2605],
        [  -15.5956],
        [-6507.7263]], dtype=torch.float64)
torch.Size([5, 1])
a1 =  tensor([[ -63.6634],
        [ -67.9938],
        [ 323.2286],
        [ -40.5077],
        [-747.7623]], dtype=torch.float64)
torch.Size([5, 1])
a0 =  tensor([[  17.4291],
        [  20.1983],
        [ 474.6261],
        [   5.7029],
        [4856.2267]], dtype=torch.float64)
torch.Size([5, 1])


9. Recovery of the polynomial roots cos (teta)

In [35]:
from torch import vmap

# Computation of the roots
roots = polynomial_root_calculation_4th_degree_ferrari(a0,a1,a2,a3,a4) # (batch_size,4)

print("roots = \n", roots)  # list of tensor (for complex numbers)


a0 = 
 tensor([[  17.4291],
        [  20.1983],
        [ 474.6261],
        [   5.7029],
        [4856.2267]], dtype=torch.float64)
torch.Size([5, 1])
a torch.Size([5, 1])
x_cube  tensor([[[ 0.1403,  0.0000],
         [-0.4313,  0.3587],
         [-0.4313, -0.3587]],

        [[ 0.0433,  0.0000],
         [ 0.2090,  0.2157],
         [ 0.2090, -0.2157]],

        [[ 0.0740,  0.0000],
         [-0.0565,  0.9445],
         [-0.0565, -0.9445]],

        [[ 0.1693,  0.0000],
         [-0.1287,  0.2262],
         [-0.1287, -0.2262]],

        [[ 1.2359,  0.0000],
         [-8.7430,  3.6207],
         [-8.7430, -3.6207]]])
torch.Size([5, 3, 2])
x_cube_real = 
 tensor([[ 0.1403, -0.4313, -0.4313],
        [ 0.0433,  0.2090,  0.2090],
        [ 0.0740, -0.0565, -0.0565],
        [ 0.1693, -0.1287, -0.1287],
        [ 1.2359, -8.7430, -8.7430]])
torch.Size([5, 3])
a.shape =  torch.Size([5, 2])
b.shape =  torch.Size([5, 1])
frac = 
 tensor([[ 0.5610,  0.0000],
        [ 0.3003,  0.0000],
     

10. For each solution : computation of the camera position and rotation matrix

In [36]:
# For each solution of the polynomial
for i in range(4):
  #if np.isclose(np.imag(roots[i]),0) : # if real solution 

    # Computation of trigonometrics forms
    cos_teta = torch.tensor(roots[i][0])# real part of the root 
    sin_teta = torch.sqrt(1-cos_teta**2)

    cot_alpha = ((phi1/phi2)*p1 + cos_teta*p2 -d12*b )/ ((phi1/phi2)*cos_teta* p2 - p1 + d12)

    sin_alpha = torch.sqrt(1/(cot_alpha**2+1))
    cos_alpha= torch.sqrt(1-sin_alpha**2)

    if cot_alpha < 0 :
      cos_alpha = -cos_alpha

    # Computation of the intermediate rotation's matrixs
    C_estimate = torch.tensor([d12*cos_alpha*(sin_alpha*b + cos_alpha), d12*sin_alpha*cos_teta*(sin_alpha*b+cos_alpha), d12*sin_alpha*sin_teta*(sin_alpha*b+cos_alpha)]) # (3,)
    print("C_estimate = \n", C_estimate)
    print(C_estimate.shape)  # (3,)
    Q = torch.tensor([[-cos_alpha, -sin_alpha*cos_teta, -sin_alpha*sin_teta], [sin_alpha, -cos_alpha*cos_teta, -cos_alpha*sin_teta], [0, -sin_teta, cos_teta]])    # (3*3)
    print("Q = \n", Q)
    print(Q.shape)  # (3,3)
    # Computation of the absolute camera center
  
    C_estimate = P1 + torch.tensordot(torch.transpose(N, 0,1), C_estimate, dims=1) # (3,)
    print("C_estimate = \n", C_estimate) 
    print(C_estimate.shape)  # (3,)
    C_estimate = torch.reshape(C_estimate, (3,1))  # Reshape to (3,1) for consistency
    print("C_estimate = \n", C_estimate)  # (3,1)
    print("C_estimate.shape = ", C_estimate.shape)  # (3,1)

    # Computation of the orientation matrix
    R_estimate = torch.tensordot(torch.tensordot(torch.transpose(N,0,1),torch.transpose(Q, 0,1), dims=1),T,dims=1)   # (3*3)
    print("R_estimate = \n", R_estimate)
    print(R_estimate.shape)  # (3,3)
    
    # Adding C and R to the solutions
    solutions[i,:,:1]= C_estimate
    solutions[i,:,1:] = R_estimate

print("solutions = \n", solutions)


C:\Users\pmamalet\AppData\Local\Temp\ipykernel_30212\4123210296.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cos_teta = torch.tensor(roots[i][0])# real part of the root


RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [ ]:
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

11. Reprojection of points in 2D from the newly estimated matrices to verify the estimation error.

In [ ]:
def projection3D2D(point3D,C,R,A) :
  # 3D point = [ Xw, Yw, Zw ]'   (1*3)
  # T : camera translation matrix : (3*1)
  # R : camera rotation matrix : (3*3)
  # A : intraseca matrix of the camera : (3*3)
  # Output : return the coordonates of the point in 2D 

  PI = torch.cat((torch.eye(3, dtype=torch.float64),torch.zeros((3,1), dtype=torch.float64)),dim=1)  # (3*4)

  Rt = torch.cat((R,C),dim=1)               # (3*4)
  Rt = torch.cat((Rt,torch.tensor([[0,0,0,1]], dtype=torch.float64)),dim=0)   # (4*4)

  point3D_bis = torch.cat((torch.reshape(point3D,(3,1)),torch.tensor([[1]],dtype=torch.float64)),dim=0)   #(4*1)
  
  point2D = torch.tensordot(torch.tensordot(torch.tensordot(A,PI,dims=1),Rt,dims=1),point3D_bis,dims=1)  # 2D point = [u, v, w] (3*1)
  point2D = point2D / point2D[2]        # 2D point = [u, v, 1] (3*1)
  return point2D[:2]


C_transpose = torch.transpose(C, 0, 1)  # (3*1) -> (1*3)

p1 = projection3D2D(P1,C_transpose,R,A)
print("p1 = ", p1)
print(p1.shape)  # (2,1)
p2 = projection3D2D(points3D[1],C_transpose,R,A)
print("p2 = ", p2)
p3 = projection3D2D(points3D[2],C_transpose,R,A)
print("p3 = ", p3)
p4 = projection3D2D(P4,C_transpose,R,A)
print("p4 = ", p4)




12. Calculation of errors = distance between the 2D points estimated from the found rotation and position matrices and the 2D points from the initial matrices

In [ ]:
def distance(pt, pt_estimation):
    erreur = torch.tensor(0, dtype=torch.float64)  # Initialize error as a tensor
    for i in range(len(pt)): 
      erreur = erreur + torch.tensor((pt[i] - pt_estimation[i])**2, dtype=torch.float64)  # Ensure each term is a tensor
      #erreur += (pt[i] - pt_estimation[i])**2
    return torch.sqrt(erreur)



def affichage_erreur(solutions,points2D,points3D,A) : 
   # Compute the error of estimation for each points after the P3P algorithm 

   # solutions : solution matrix returned by P3P (4*3*4)
   # points 3D : 4 pts 3D used for P3P 
   # points 2D : 4 pts 2D used for P3P (image of the 3D points)
   
   P1 = points3D[0]
   P2 = points3D[1]
   P3 = points3D[2]
   P4 = points3D[3]

   erreurs = []
   nb_sol = 0

   for i in range(len(solutions)) : 
      R = solutions[i,:,1:] 
      C = solutions[i,:,:1]

      if not torch.all(R==torch.zeros((3,3))) : 
        nb_sol += 1 
        print("------------ Solution n° : ",nb_sol,"----------------")
        print("R = \n",R,)
        print("T = \n",C,)

        p1_P3P = torch.reshape(projection3D2D(P1,C,R,A),(1,2))
        p2_P3P = torch.reshape(projection3D2D(P2,C,R,A),(1,2))
        p3_P3P = torch.reshape(projection3D2D(P3,C,R,A),(1,2))
        p4_P3P = torch.reshape(projection3D2D(P4,C,R,A),(1,2))
        pt_2D_P3P = torch.cat((p1_P3P,p2_P3P,p3_P3P,p4_P3P),dim=0)    # (4,2)

        erreurs.append([0])
        for j in range(len(points2D)):
            erreur_pt = distance(points2D[j],pt_2D_P3P[j])
            erreurs[i]+=erreur_pt
        
   indice_min = 0
   min = erreurs[0]
   for i in range(1,len(erreurs)) :
    if erreurs[i]<min :
      min = erreurs[i]
      indice_min = i

   R_opti = solutions[indice_min,:,1:] 
   C_opti = solutions[indice_min,:,:1]
   print("\n------------ Best solution : ----------------")
   print("Solution n° :",indice_min+1,"\n")
   print("R estimé = \n", R_opti,"\n")
   print("T estimé = \n", C_opti, "\n")

In [ ]:
affichage_erreur(solutions, [p1, p2, p3, p4], [P1,P2,P3, P4], A)