In [8]:
import numpy as np 
import torch

batch_size = 5 

At first we have : 
- camera's parameters -> A (focal, center) 
- rotation matrix  -> R 
- position matrix -> C 
- 3D points position ->  P1 P2 P3 (and P4 to determinate the best solution after P3P)

In [9]:
# This script defines the camera parameters, rotation matrix, and translation matrix.
def camera() : 
  # Definition of the camera parameters
  # focal length
  fx = 800
  fy = 800
  # center
  cx = 320 
  cy = 240

  A = torch.tensor([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=torch.float64) # intraseca matrix of the camera (3*3)
  #A = torch.from_numpy(A)  # Convert to a PyTorch tensor
  print("A = \n", A)
  print(A.shape)  # (3*3)
  A_batch = A.repeat(batch_size,1,1)
  print("A_batch = \n", A_batch)
  print(A_batch.shape)  # (batch_size, 3, 3)
  return A_batch

A = camera() 



def rotation_matrix() : 
  # Definition of the rotation matrix of the camera 
  R = torch.tensor([[1, 0, 0],[0, -1, 0], [0, 0, -1]], dtype=torch.float64)  # (3*3)
  #R = torch.from_numpy(R)  # Convert to a PyTorch tensor
  print("R = \n",R)
  print(R.shape)  # (3*3)
  R_batch = R.repeat(batch_size,1,1)  # Repeat the rotation matrix for each batch
  print("R_batch = \n", R_batch)  
  print(R_batch.shape)  # (batch_size, 3, 3)
  return R_batch

def camera_position() : 
  # Definition of the translation matrix of the camera (the position)
  C = torch.tensor([[0,0,6]], dtype=torch.float64)    # T = [tx,ty,tz]  (1*3)
  print("C = \n",C)
  print(C.shape)  # (1*3)

  C_batch = C.repeat(batch_size, 1)  # Repeat the translation vector for each batch
  print("C_batch = \n", C_batch)  
  print(C_batch.shape)  # (batch_size, 3)

 
  return C_batch

R = rotation_matrix()
C = camera_position()

A = 
 tensor([[800.,   0., 320.],
        [  0., 800., 240.],
        [  0.,   0.,   1.]], dtype=torch.float64)
torch.Size([3, 3])
A_batch = 
 tensor([[[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]]], dtype=torch.float64)
torch.Size([5, 3, 3])
R = 
 tensor([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]], dtype=torch.float64)
torch.Size([3, 3])
R_batch = 
 tensor([[[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.

In [10]:
# Definition of 3D points in the world coordinate system
def point3Daleatoire(x) :
  # Generation of one random points in 3D space 
  return torch.tensor([[np.random.uniform(-x,x),np.random.uniform(-x,x),np.random.uniform(-x,x)]])

def pts_3D_4pts():
  # Generate randomly 4 3D points
  # Output : tensor which concatenate the 4 points = [ P1, P2, P3, P4 ] 

  P1 = point3Daleatoire(2)     # (1*3) -> pour P3P
  P2 = point3Daleatoire(2)
  P3 = point3Daleatoire(2)
  P4 = point3Daleatoire(2)
  
  points3D = torch.cat((P1,P2,P3,P4),dim=0);     # (LIGNES 4* COLONNES 3) - xyz
  print("points3D = \n", points3D)
  print(points3D.shape)  # (4*3)

  
  return points3D

def pts_3D_4pts_batch():
  # Generate randomly 4 3D points for each batch
  # Output : array which concatenate the 4 points = [ P1, P2, P3, P4 ] for each batch

  # Generate a batch of random points in 3D space
  # Each point is generated independently for each batch

  points3D_batch = torch.stack([pts_3D_4pts() for i in range(batch_size)])  # (batch_size, 4, 3)
  print("points3D_batch = \n", points3D_batch)
  print(points3D_batch.shape)  # (batch_size, 4, 3)
  return points3D_batch

points3D_batch = pts_3D_4pts_batch()  # Generate the batch of 3D points
'''
P1 = torch.tensor([0.7161, 0.5431, 1.7807], dtype=torch.float64)    # (3,)
P2 = torch.tensor([-1.1643, 0.8371, -1.0551], dtype=torch.float64)
P3 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64)
P4 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64) 
'''
P1 = points3D_batch[:, 0, :]  # Extract P1 for each batch
P2 = points3D_batch[:, 1, :]  # Extract P2 for each batch
P3 = points3D_batch[:, 2, :]  # Extract P3 for each batch
P4 = points3D_batch[:, 3, :]  # Extract P4 for each batch

print("P1 = \n", P1)
print(P1.shape)  # (batch_size, 3)


points3D = 
 tensor([[-0.4336,  1.2735,  1.3707],
        [-1.4018,  0.2368,  1.2999],
        [-1.7486, -0.8187,  0.6125],
        [-1.6914,  0.0598, -0.5561]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.7995,  0.4201,  0.0132],
        [ 0.7036, -0.1004, -0.5404],
        [-0.8722, -1.1441, -1.6584],
        [ 0.7110,  0.3175,  1.5805]])
torch.Size([4, 3])
points3D = 
 tensor([[ 1.5382,  0.3528,  0.0984],
        [ 0.1061, -0.8137, -1.8533],
        [ 0.5140, -0.8249,  1.0075],
        [-0.8183,  0.6201, -0.1573]])
torch.Size([4, 3])
points3D = 
 tensor([[-0.5543,  0.2068,  0.0388],
        [ 0.7492,  1.6988,  0.9027],
        [ 0.1988, -1.0855, -0.3351],
        [-0.0565,  1.2946,  1.3896]])
torch.Size([4, 3])
points3D = 
 tensor([[-0.5095, -1.5698,  1.3310],
        [-0.7759,  0.8086, -1.0455],
        [ 1.0033, -0.2136,  1.8101],
        [ 1.9835, -1.3274, -0.2711]])
torch.Size([4, 3])
points3D_batch = 
 tensor([[[-0.4336,  1.2735,  1.3707],
         [-1.4018,  0.2368,  1.2999],


We create the 3 direction features vectors f1, f2, f3

In [12]:
def features_vectors(points3D,C, R,batch_size) :
    '''
    This function computes the features vectors for P3P algorithm.
    args:
    points3D : array with the 4 3D points = [ P1, P2, P3, P4 ] (4*3) 
    but we only use the first three points for P3P
    C: camera position matrix : (3*1)
    returns:
    featuresVect : array with the features vectors (9*1)
    '''
    P1 = torch.reshape(points3D[0], (batch_size,3,1))  # Reshape to (3,1) for easier calculations
    print("P1 = \n", P1)  # Print P1 to check the values
    print(P1.shape)  # (batch_size, 3, 1)
    P2 = torch.reshape(points3D[1], (batch_size,3,1))
    P3 = torch.reshape(points3D[2], (batch_size,3,1))

    C = torch.reshape(C, (batch_size,3,1))  # Reshape C to (3,1) for easier calculations
    print("C = \n", C)  # Print C to check the values
    print(C.shape)  # (batch_size, 3, 1)

    v1 = torch.matmul(R,(P1 - C))  # Calculate the vector from camera to P1
    print("v1 = \n", v1)  # Print v1 to check the values
    print(v1.shape)  # (batch_size, 3, 1)
    v2 = torch.matmul(R,(P2 - C))  # Calculate the vector from camera to P2
    v3 = torch.matmul(R,(P3 - C))  # Calculate the vector from camera to P3

    f1 = v1 / torch.norm(v1,dim=1, keepdim=True)  # Normalize the vector v1
    f2 = v2 / torch.norm(v2,dim=1, keepdim=True)  # Normalize the vector v2
    f3 = v3 / torch.norm(v3,dim=1, keepdim=True)  # Normalize the vector v3

    print("f1 = \n", f1)  # Print f1 to check the values
    print(f1.shape)  # (batch_size, 3, 1)

    f1 = torch.reshape(f1, (batch_size,1,3))  # Reshape to (3,1)
    print("f1 : ",f1.shape) # (batch_size,1,3)
    f2 = torch.reshape(f2, (batch_size,1,3))
    f3 = torch.reshape(f3, (batch_size,1,3))

    featuresVect = torch.cat((f1,f2,f3),dim=1)
    print("features vectors = \n",featuresVect)
    print(featuresVect.shape)  # (batch_size, 3, 3)

    return featuresVect # Return the features vectors need in P3P


points3D = [P1, P2, P3]  # We define the points3D with the first three points
print("points3D = \n", points3D)  # Print the points3D to check the values  / List len = 3 


featuresVect = features_vectors(points3D, C, R,batch_size)  

points3D = 
 [tensor([[-0.4336,  1.2735,  1.3707],
        [-1.7995,  0.4201,  0.0132],
        [ 1.5382,  0.3528,  0.0984],
        [-0.5543,  0.2068,  0.0388],
        [-0.5095, -1.5698,  1.3310]]), tensor([[-1.4018,  0.2368,  1.2999],
        [ 0.7036, -0.1004, -0.5404],
        [ 0.1061, -0.8137, -1.8533],
        [ 0.7492,  1.6988,  0.9027],
        [-0.7759,  0.8086, -1.0455]]), tensor([[-1.7486, -0.8187,  0.6125],
        [-0.8722, -1.1441, -1.6584],
        [ 0.5140, -0.8249,  1.0075],
        [ 0.1988, -1.0855, -0.3351],
        [ 1.0033, -0.2136,  1.8101]])]
P1 = 
 tensor([[[-0.4336],
         [ 1.2735],
         [ 1.3707]],

        [[-1.7995],
         [ 0.4201],
         [ 0.0132]],

        [[ 1.5382],
         [ 0.3528],
         [ 0.0984]],

        [[-0.5543],
         [ 0.2068],
         [ 0.0388]],

        [[-0.5095],
         [-1.5698],
         [ 1.3310]]])
torch.Size([5, 3, 1])
C = 
 tensor([[[0.],
         [0.],
         [6.]],

        [[0.],
         [0.],
   

Lastly we need the functions to resolve the polynomial roots. - for test go to test resolution polynome 

In [73]:
from complex_utils import *

def polynomial_root_calculation_3rd_degree(a, b, c, d):
    '''# Convert to complex tensors
    a = torch.tensor(a, dtype=torch.complex64)
    b = torch.tensor(b, dtype=torch.complex64)
    c = torch.tensor(c, dtype=torch.complex64)
    d = torch.tensor(d, dtype=torch.complex64)'''

    # Discriminant terms
    p = (3 * a * c - b**2) / (3 * a**2)
    q = (2 * b**3 - 9 * a * b * c + 27 * a**2 * d) / (27 * a**3)
    delta = -4 * p**3 - 27 * q**2
    roots = []

    j_ = torch.tensor([-0.5, torch.sqrt(torch.tensor(3))/2])  # cube root of unity

    k = torch.tensor([0,1,2])

    delta_sur_27 = -delta / 27          # reéls

    sqrt_term = sqrt(delta_sur_27)  # Use the sqrt function defined above
    u_k = product_of_2_complex_numbers(complex_number_power_k(j_,k), sqrt_3(torch.tensor([0.5*(-q+sqrt_term[0]),sqrt_term[1]])) )# because q real 
    v_k = product_of_2_complex_numbers(complex_number_power_k(j_,-k), sqrt_3(torch.tensor([0.5*(-q-sqrt_term[0]),-0.5*sqrt_term[1]])))

    root = addition(addition(u_k, v_k), torch.tensor([-b/(3*a),0]) ) 
    roots.append(root)

    return torch.stack(roots)

def polynomial_root_calculation_4th_degree_ferrari(a): # Ferrari's Method
    # Solving a polynomial of 4th degree

    # Input : array 5*1 with the 5 coefficiants of the polynomial 
    # Output : roots of the polynomial a[4]*x^4 + a[3]*x^3 + a[2]*x^2 + a[1]*x + a[0]   -> array : [x1,x2,x3,x4]  (4*1)

    if a.numel() != 5 :
      print("Expeted 5 coefficiants for a 4th order polynomial")
      return

    a0, a1, a2, a3, a4 = a      # float

    # Reduce the quartic equation to the form : x^4 + a*x^3 + b*x^2 + c*x + d = 0
    a = a3/a4           # float 
    b = a2/a4
    c = a1/a4
    d = a0/a4

    # Computation of the coefficients of the Ferrari's Method
    S = a/4
    b0 = d - c*S + b* S**2 - 3* S**4
    b1 = c - 2*b*S + 8*S**3
    b2 = b - 6 * S**2


    # Solve the cubic equation m^3 + b2*m^2 + (b2^2/4  - b0)*m - b1^2/8 = 0
    x_cube = polynomial_root_calculation_3rd_degree(1,b2,(b2**2)/4-b0,(-b1**2)/8)
    

    # Find a real and positive solution
    condition = (torch.isclose(x_cube[:,1],torch.tensor(0.0,dtype=torch.float64),atol=1e-7)) & (x_cube[:,0] > 0) 
    condition_respected = x_cube[condition]  # Get the indices of the roots that respect the condition

    print("indices_respect_condition = \n", condition_respected)  # Print the indices of the roots that respect the condition
    alpha_0_nul = condition_respected.shape[0] == 0

    if not alpha_0_nul : 
       alpha_0 = condition_respected[-1]


    if alpha_0_nul == False :   # case where we found a real and positive solution so alpha_0_imag = 0 
        alpha0_div_2 = product_complex_real(alpha_0,0.5)
        sqrt_alpha = sqrt(alpha0_div_2[0])
        term = addition_complex_real(- alpha0_div_2 ,-b2 / 2)
        denom = 2 * torch.sqrt(2 * alpha_0)
        
       
        frac = division_2_complex_numbers(torch.tensor([b1, 0.0]), denom)  # b1 is real, so we can use a tensor with 0 imaginary part

        x1 = addition_complex_real(sqrt_alpha ,- S) + sqrt_complex(addition(term,-frac))
        x2 = addition_complex_real(sqrt_alpha, - S) - sqrt_complex(addition(term,-frac))
        x3 = addition_complex_real(-sqrt_alpha, - S) + sqrt_complex(addition(term,frac))
        x4 = addition_complex_real(-sqrt_alpha,- S) - sqrt_complex(addition(term,frac))
    
    else:

        sqrt_inner1 = sqrt((b2**2) / 4 - b0)        # complex 
        x1 = addition_complex_real(sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x2 = addition_complex_real(- sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x3 = addition_complex_real(sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)
        x4 = addition_complex_real(- sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)

    return torch.tensor([x1, x2, x3, x4])




We have all the variables needed for the p3p so we start

1. Storage of points : already done 

In [74]:
print("P1 = \n", P1)
print("P2 = \n", P2)
print("P3 = \n", P3)

P1 = 
 tensor([[-0.4336,  1.2735,  1.3707],
        [-1.7995,  0.4201,  0.0132],
        [ 1.5382,  0.3528,  0.0984],
        [-0.5543,  0.2068,  0.0388],
        [-0.5095, -1.5698,  1.3310]])
P2 = 
 tensor([[-1.4018,  0.2368,  1.2999],
        [ 0.7036, -0.1004, -0.5404],
        [ 0.1061, -0.8137, -1.8533],
        [ 0.7492,  1.6988,  0.9027],
        [-0.7759,  0.8086, -1.0455]])
P3 = 
 tensor([[-1.7486, -0.8187,  0.6125],
        [-0.8722, -1.1441, -1.6584],
        [ 0.5140, -0.8249,  1.0075],
        [ 0.1988, -1.0855, -0.3351],
        [ 1.0033, -0.2136,  1.8101]])


2. Storage of the features vectors : done

In [21]:
# we got featuresVect and we access the 3 values 
f1 = featuresVect[:,0,:]  # Access the first feature vector for each batch
f2 = featuresVect[:,1,:]
f3 = featuresVect[:,2,:]

print("f1 = ", f1)
print(f1.shape)  # (batsh_size,3)
print("f2 = ", f2)
print(f2.shape)  # (batsh_size,3)
print("f3 = ", f3)
print(f3.shape)  # (batsh_size,3)

f1 =  tensor([[-0.0899, -0.2642,  0.9603],
        [-0.2872, -0.0671,  0.9555],
        [ 0.2518, -0.0578,  0.9661],
        [-0.0925, -0.0345,  0.9951],
        [-0.1029,  0.3170,  0.9428]], dtype=torch.float64)
torch.Size([5, 3])
f2 =  tensor([[-0.2855, -0.0482,  0.9572],
        [ 0.1069,  0.0153,  0.9941],
        [ 0.0134,  0.1030,  0.9946],
        [ 0.1381, -0.3131,  0.9396],
        [-0.1088, -0.1133,  0.9876]], dtype=torch.float64)
torch.Size([5, 3])
f3 =  tensor([[-0.3055,  0.1431,  0.9414],
        [-0.1119,  0.1468,  0.9828],
        [ 0.1011,  0.1622,  0.9816],
        [ 0.0309,  0.1688,  0.9852],
        [ 0.2326,  0.0495,  0.9713]], dtype=torch.float64)
torch.Size([5, 3])


3. Création of a solution variable : maximum 4 solutions  

    Matrix (4,3,4)  
    Each layer is a solution, for each leayer : first column stres the camera position matrix C (3,1) and the remaining 3 columns store the rotation matrix R (3,3)

In [22]:
solutions = torch.zeros((batch_size,4,3,4), dtype=torch.float64)
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

solutions = 
 tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
        

4. Verification that the 3 points given are not collinear 

In [23]:
# Test of non-collinearity
v1 = P2 - P1
print("v1 = \n", v1)  # Print v1 to check the values
print(v1.shape)  # (batch_size, 3)
v2 = P3 - P1

norms = torch.norm(torch.cross(v1,v2, dim=1),dim = 1 )
print("norms : ",norms.shape)  # (batch_size,)

all_dif_zero = torch.all(norms != 0)  # Check if all norms are non-zero

if not all_dif_zero:
    print('\nProblem: the points must not be collinear')
else:
    print('\nThe points are not collinear, we can continue')

v1 = 
 tensor([[-0.9683, -1.0367, -0.0708],
        [ 2.5031, -0.5205, -0.5536],
        [-1.4320, -1.1665, -1.9518],
        [ 1.3035,  1.4920,  0.8639],
        [-0.2663,  2.3784, -2.3765]])
torch.Size([5, 3])
norms :  torch.Size([5])

The points are not collinear, we can continue


5. Creation of an orthonormal frame from f1, f2, f3 (the features vectors)

In [28]:
# Calculation of vectors of the base τ = (C,tx,ty,tz)
tx = f1     
print("tx = ", tx)
print(tx.shape)  # (batch_size,3)

tz = torch.cross(f1,f2,dim=1)/ torch.norm(torch.cross(f1,f2,dim=1),dim=1, keepdim=True)  # Normalize the cross product to get tz
print("tz = ", tz)
print(tz.shape)  # (batch_size,3)

ty = torch.cross(tz,tx,dim=1)
print("ty = ", ty)
print(ty.shape)  # (batch_size,3)

tx =  tensor([[-0.0899, -0.2642,  0.9603],
        [-0.2872, -0.0671,  0.9555],
        [ 0.2518, -0.0578,  0.9661],
        [-0.0925, -0.0345,  0.9951],
        [-0.1029,  0.3170,  0.9428]], dtype=torch.float64)
torch.Size([5, 3])
tz =  tensor([[-0.7166, -0.6525, -0.2466],
        [-0.2051,  0.9787,  0.0070],
        [-0.5491, -0.8305,  0.0935],
        [ 0.7760,  0.6237,  0.0938],
        [ 0.9940, -0.0022,  0.1092]], dtype=torch.float64)
torch.Size([5, 3])
ty =  tensor([[-0.6917,  0.7103,  0.1306],
        [ 0.9357,  0.1939,  0.2949],
        [-0.7969,  0.5540,  0.2408],
        [ 0.6239, -0.7809,  0.0309],
        [-0.0367, -0.9484,  0.3149]], dtype=torch.float64)
torch.Size([5, 3])


5. (bis) Creation of a transformation matrix T and expression of the f3 vector in this frame

In [42]:
tx = torch.reshape(tx,(batch_size,1,3))   # (batch_sizee,1,3)
print("tx = \n", tx)
print(tx.shape)  # (batch_size,1,3)

ty = torch.reshape(ty,(batch_size,1,3))
print("ty = \n", ty)
print(ty.shape)  # (batch_size,1,3)

tz = torch.reshape(tz,(batch_size,1,3))
print("tz = \n", tz)
print(tz.shape)  # (batch_size,1,3)

# Computation of the matrix T and the feature vector f3
T = torch.cat((tx,ty,tz),dim = 1) # (3*3)
print("T = \n", T)
print(T.shape)  # (batch_size,3,3)


f3_T = torch.matmul(T,f3.unsqueeze(-1)) # (
print("f3_T = \n", f3_T)
print(f3_T.shape)  # (batch_size,3,1)


tx = 
 tensor([[[-0.0899, -0.2642,  0.9603]],

        [[-0.2872, -0.0671,  0.9555]],

        [[ 0.2518, -0.0578,  0.9661]],

        [[-0.0925, -0.0345,  0.9951]],

        [[-0.1029,  0.3170,  0.9428]]], dtype=torch.float64)
torch.Size([5, 1, 3])
ty = 
 tensor([[[-0.6917,  0.7103,  0.1306]],

        [[ 0.9357,  0.1939,  0.2949]],

        [[-0.7969,  0.5540,  0.2408]],

        [[ 0.6239, -0.7809,  0.0309]],

        [[-0.0367, -0.9484,  0.3149]]], dtype=torch.float64)
torch.Size([5, 1, 3])
tz = 
 tensor([[[-0.7166, -0.6525, -0.2466]],

        [[-0.2051,  0.9787,  0.0070]],

        [[-0.5491, -0.8305,  0.0935]],

        [[ 0.7760,  0.6237,  0.0938]],

        [[ 0.9940, -0.0022,  0.1092]]], dtype=torch.float64)
torch.Size([5, 1, 3])
T = 
 tensor([[[-0.0899, -0.2642,  0.9603],
         [-0.6917,  0.7103,  0.1306],
         [-0.7166, -0.6525, -0.2466]],

        [[-0.2872, -0.0671,  0.9555],
         [ 0.9357,  0.1939,  0.2949],
         [-0.2051,  0.9787,  0.0070]],

        [[ 0

The sing of the z-coordinate in f3_T give us the sign of teta, that we will need after 

In [ ]:
print(f3_T[:,2])
f3_T_positif = f3_T[:,2] > 0

print("f3_T_positif = \n", f3_T_positif)
print(f3_T_positif.shape)  # (batch_size,1)

tensor([[-0.1065],
        [ 0.1736],
        [-0.0984],
        [ 0.2217],
        [ 0.3372]], dtype=torch.float64)
f3_T_positif = 
 tensor([[False],
        [ True],
        [False],
        [ True],
        [ True]])
torch.Size([5, 1])


6. Change of frame is performed on the 3D points side, and the transformation matrix N is defined

In [ ]:
# Calculation of vectors of the base η = (P1,nx,ny,nz)
nx = (P2 - P1)/torch.norm(P2 - P1,dim=1,keepdim=True)      #(batch_size,3)
print("nx : ", nx.shape)  # (batch_size,3)

nz = torch.cross(nx,P3-P1,dim=1)/torch.norm(torch.cross(nx,P3-P1,dim=1), dim=1, keepdim=True) 
print("nz : ", nz.shape)  # (batch_size,3)

ny = torch.cross(nz,nx,dim=1)
print("ny : ", ny.shape)  # (batch_size,3)


# Reshape the vectors to (1,3) for concatenation
nx = torch.reshape(nx,(batch_size,1,3))  # (batch_size,1,3)
ny = torch.reshape(ny,(batch_size,1,3))
nz = torch.reshape(nz,(batch_size,1,3))

print("nx = \n", nx)
print(nx.shape)  # (1*3)
print("ny = \n", ny)
print("nz = \n", nz)

# Computation of the matrix N and the world point P3
N = torch.cat((nx,ny,nz),dim = 1) #  T's equivalent in the world coordinate system
print("N = \n", N)
print(N.shape)  # (batch_size,3,3)

print("P3.shape = ", P3.shape)  # (batch_size,3)

P3_n = torch.matmul(N,(P3-P1).unsqueeze(-1)) 


print("P3_n = \n", P3_n)
print(P3_n.shape)  # (5,3,1)


nx :  torch.Size([5, 3])
nz :  torch.Size([5, 3])
ny :  torch.Size([5, 3])
nx = 
 tensor([[[-0.6817, -0.7299, -0.0499]],

        [[ 0.9569, -0.1990, -0.2116]],

        [[-0.5329, -0.4341, -0.7263]],

        [[ 0.6031,  0.6903,  0.3997]],

        [[-0.0790,  0.7052, -0.7046]]])
torch.Size([5, 1, 3])
ny = 
 tensor([[[ 0.4599, -0.3746, -0.8051]],

        [[-0.2905, -0.6534, -0.6991]],

        [[-0.4612, -0.5706,  0.6794]],

        [[ 0.7768, -0.6221, -0.0976]],

        [[ 0.7658,  0.4954,  0.4100]]])
nz = 
 tensor([[[ 5.6896e-01, -5.7179e-01,  5.9105e-01]],

        [[ 8.0737e-04,  7.3040e-01, -6.8302e-01]],

        [[-7.0942e-01,  6.9708e-01,  1.0390e-01]],

        [[ 1.8129e-01,  3.6933e-01, -9.1144e-01]],

        [[ 6.3816e-01, -5.0725e-01, -5.7917e-01]]])
N = 
 tensor([[[-6.8173e-01, -7.2990e-01, -4.9859e-02],
         [ 4.5992e-01, -3.7457e-01, -8.0509e-01],
         [ 5.6896e-01, -5.7179e-01,  5.9105e-01]],

        [[ 9.5688e-01, -1.9897e-01, -2.1164e-01],
         [-2.9

7. Definition of the variables for the following steps 

In [68]:
# Computation of phi1 et phi2 with 0=x, 1=y, 2=z
phi1 = f3_T[:,0]/f3_T[:,2]
phi2 = f3_T[:,1]/f3_T[:,2]
print("phi1 = ", phi1)
print(phi1.shape)  # (batch_size,1)
print("phi2 = ", phi2)
print(phi2.shape)  # (batch_size,1)

# Extraction of p1 and p2 from P3_eta
p1 = P3_n[:,0] #x
p2 = P3_n[:,1] #y
print("p1 = ", p1)
print(p1.shape)  # (batch_size,3)
print("p2 = ", p2)
print(p2.shape)  # (batch_size,3)

# Computation of d12
d12 = torch.norm(P2-P1,dim=1, keepdim=True) 
print("d12 = ", d12)
print(d12.shape)  # (batch_size,1)

# Computation of b = cot(beta)
cosBeta =( torch.sum(f1*f2,dim=1)/(torch.norm(f1,dim=1)*torch.norm(f2,dim=1)) ).unsqueeze(-1)  # tensor.dot(a,b) <=> tensor.sum(a*b)
print("cosBeta = ", cosBeta)  
print(cosBeta.shape)  # (batch_size,1)

b = torch.sqrt(1/(1-cosBeta**2)-1)
print("b = ", b)
print(b.shape)  # (batch_size,1)

b = torch.where(cosBeta < 0, -b, b)  # If cosBeta < 0, then b = -b
print("b = ", b)
print(b.shape)  # (batch_size,1)

phi1 =  tensor([[-8.3881],
        [ 5.5387],
        [-9.7957],
        [ 4.3832],
        [ 2.6916]], dtype=torch.float64)
torch.Size([5, 1])
phi2 =  tensor([[-4.0914],
        [ 1.2302],
        [-2.4958],
        [-0.3703],
        [ 0.7425]], dtype=torch.float64)
torch.Size([5, 1])
p1 =  tensor([[ 2.4614],
        [ 1.5524],
        [ 0.3968],
        [-0.5873],
        [ 0.4993]])
torch.Size([5, 1])
p2 =  tensor([[0.7893],
        [1.9213],
        [1.7620],
        [1.4255],
        [2.0269]])
torch.Size([5, 1])
d12 =  tensor([[1.4203],
        [2.6159],
        [2.6871],
        [2.1614],
        [3.3727]])
torch.Size([5, 1])
cosBeta =  tensor([[0.9576],
        [0.9182],
        [0.9583],
        [0.9330],
        [0.9064]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[3.3223],
        [2.3178],
        [3.3517],
        [2.5935],
        [2.1456]], dtype=torch.float64)
torch.Size([5, 1])
b =  tensor([[3.3223],
        [2.3178],
        [3.3517],
        [2.5935],
   

8. Calculation of the coefficients of the polynomial 

In [69]:
a4 = - phi2**2 * p2**4 - phi1**2 * p2**4 - p2**4
a3 = 2 * p2**3 * d12 * b + 2 * phi2**2 * p2**3 * d12 * b - 2 * phi1 * phi2 * p2**3 * d12
a2 = - phi2**2 * p1**2 * p2**2 - phi2**2 * p2**2 * d12**2 * b**2 - phi2**2 * p2**2 * d12**2 + phi2**2 * p2**4 + phi1**2 * p2 **4 + 2 * p1 * p2**2 * d12 + 2 * phi1 * phi2 * p1 * p2**2 * d12 * b - phi1**2 * p1**2 * p2**2 + 2 * phi2**2 * p1 * p2**2 * d12 - p2**2 * d12**2 * b**2 - 2 * p1**2 * p2**2
a1 = 2 * p1**2 * p2 * d12 * b + 2 * phi1 * phi2 * p2**3 * d12 - 2 * phi2**2 * p2**3 * d12 * b - 2 * p1 * p2 * d12**2 * b
a0 = - 2 * phi1 * phi2 * p1 * p2**2 * d12 * b + phi2**2 * p2**2 * d12**2 + 2 * p1**3 * d12 - p1**2 * d12**2 + phi2**2 * p1**2 * p2**2 - p1**4 - 2 * phi2**2 * p1 * p2**2 * d12 + phi1**2 * p1**2 * p2**2 + phi2**2 * p2**2 * d12**2 * b**2

print("a4 = ", a4)
print(a4.shape)  # (batch_size,1)
print("a3 = ", a3)
print("a3.shape = ", a3.shape)  # (batch_size,1)
print("a2 = ", a2)
print(a2.shape)  # (batch_size,1)
print("a1 = ", a1)
print(a1.shape)  # (batch_size,1)
print("a0 = ", a0)
print(a0.shape)  # (batch_size,1)


a4 =  tensor([[ -34.1934],
        [-452.2740],
        [-994.6210],
        [ -84.0288],
        [-148.4714]], dtype=torch.float64)
torch.Size([5, 1])
a3 =  tensor([[ 34.3855],
        [-36.6696],
        [ -6.4190],
        [ 57.2493],
        [ 74.7082]], dtype=torch.float64)
a3.shape =  torch.Size([5, 1])
a2 =  tensor([[   4.3184],
        [ 304.0250],
        [-435.8506],
        [   6.8745],
        [-157.1612]], dtype=torch.float64)
torch.Size([5, 1])
a1 =  tensor([[-10.6573],
        [ 84.2075],
        [ 76.1178],
        [  1.0279],
        [  3.7309]], dtype=torch.float64)
torch.Size([5, 1])
a0 =  tensor([[5.8565e+00],
        [8.3859e+00],
        [1.1738e+03],
        [4.1781e-03],
        [8.3338e+01]], dtype=torch.float64)
torch.Size([5, 1])


9. Recovery of the polynomial roots cos (teta)

In [78]:
from torch import vmap

# Computation of the roots
roots = vmap(polynomial_root_calculation_4th_degree_ferrari)(torch.cat([a0,a1,a2,a3,a4],dim=1)) # (batch_size,4)

print("roots = \n", roots)  # list of tensor (for complex numbers)


RuntimeError: vmap: It looks like you're attempting to use a Tensor in some data-dependent control flow. We don't support that yet, please shout over at https://github.com/pytorch/functorch/issues/257 .

10. For each solution : computation of the camera position and rotation matrix

In [ ]:
# For each solution of the polynomial
for i in range(4):
  #if np.isclose(np.imag(roots[i]),0) : # if real solution 

    # Computation of trigonometrics forms
    cos_teta = torch.tensor(roots[i][0])# real part of the root 
    sin_teta = torch.sqrt(1-cos_teta**2)

    cot_alpha = ((phi1/phi2)*p1 + cos_teta*p2 -d12*b )/ ((phi1/phi2)*cos_teta* p2 - p1 + d12)

    sin_alpha = torch.sqrt(1/(cot_alpha**2+1))
    cos_alpha= torch.sqrt(1-sin_alpha**2)

    if cot_alpha < 0 :
      cos_alpha = -cos_alpha

    # Computation of the intermediate rotation's matrixs
    C_estimate = torch.tensor([d12*cos_alpha*(sin_alpha*b + cos_alpha), d12*sin_alpha*cos_teta*(sin_alpha*b+cos_alpha), d12*sin_alpha*sin_teta*(sin_alpha*b+cos_alpha)]) # (3,)
    print("C_estimate = \n", C_estimate)
    print(C_estimate.shape)  # (3,)
    Q = torch.tensor([[-cos_alpha, -sin_alpha*cos_teta, -sin_alpha*sin_teta], [sin_alpha, -cos_alpha*cos_teta, -cos_alpha*sin_teta], [0, -sin_teta, cos_teta]])    # (3*3)
    print("Q = \n", Q)
    print(Q.shape)  # (3,3)
    # Computation of the absolute camera center
  
    C_estimate = P1 + torch.tensordot(torch.transpose(N, 0,1), C_estimate, dims=1) # (3,)
    print("C_estimate = \n", C_estimate) 
    print(C_estimate.shape)  # (3,)
    C_estimate = torch.reshape(C_estimate, (3,1))  # Reshape to (3,1) for consistency
    print("C_estimate = \n", C_estimate)  # (3,1)
    print("C_estimate.shape = ", C_estimate.shape)  # (3,1)

    # Computation of the orientation matrix
    R_estimate = torch.tensordot(torch.tensordot(torch.transpose(N,0,1),torch.transpose(Q, 0,1), dims=1),T,dims=1)   # (3*3)
    print("R_estimate = \n", R_estimate)
    print(R_estimate.shape)  # (3,3)
    
    # Adding C and R to the solutions
    solutions[i,:,:1]= C_estimate
    solutions[i,:,1:] = R_estimate

print("solutions = \n", solutions)


In [ ]:
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

11. Reprojection of points in 2D from the newly estimated matrices to verify the estimation error.

In [ ]:
def projection3D2D(point3D,C,R,A) :
  # 3D point = [ Xw, Yw, Zw ]'   (1*3)
  # T : camera translation matrix : (3*1)
  # R : camera rotation matrix : (3*3)
  # A : intraseca matrix of the camera : (3*3)
  # Output : return the coordonates of the point in 2D 

  PI = torch.cat((torch.eye(3, dtype=torch.float64),torch.zeros((3,1), dtype=torch.float64)),dim=1)  # (3*4)

  Rt = torch.cat((R,C),dim=1)               # (3*4)
  Rt = torch.cat((Rt,torch.tensor([[0,0,0,1]], dtype=torch.float64)),dim=0)   # (4*4)

  point3D_bis = torch.cat((torch.reshape(point3D,(3,1)),torch.tensor([[1]],dtype=torch.float64)),dim=0)   #(4*1)
  
  point2D = torch.tensordot(torch.tensordot(torch.tensordot(A,PI,dims=1),Rt,dims=1),point3D_bis,dims=1)  # 2D point = [u, v, w] (3*1)
  point2D = point2D / point2D[2]        # 2D point = [u, v, 1] (3*1)
  return point2D[:2]


C_transpose = torch.transpose(C, 0, 1)  # (3*1) -> (1*3)

p1 = projection3D2D(P1,C_transpose,R,A)
print("p1 = ", p1)
print(p1.shape)  # (2,1)
p2 = projection3D2D(points3D[1],C_transpose,R,A)
print("p2 = ", p2)
p3 = projection3D2D(points3D[2],C_transpose,R,A)
print("p3 = ", p3)
p4 = projection3D2D(P4,C_transpose,R,A)
print("p4 = ", p4)




12. Calculation of errors = distance between the 2D points estimated from the found rotation and position matrices and the 2D points from the initial matrices

In [ ]:
def distance(pt, pt_estimation):
    erreur = torch.tensor(0, dtype=torch.float64)  # Initialize error as a tensor
    for i in range(len(pt)): 
      erreur = erreur + torch.tensor((pt[i] - pt_estimation[i])**2, dtype=torch.float64)  # Ensure each term is a tensor
      #erreur += (pt[i] - pt_estimation[i])**2
    return torch.sqrt(erreur)



def affichage_erreur(solutions,points2D,points3D,A) : 
   # Compute the error of estimation for each points after the P3P algorithm 

   # solutions : solution matrix returned by P3P (4*3*4)
   # points 3D : 4 pts 3D used for P3P 
   # points 2D : 4 pts 2D used for P3P (image of the 3D points)
   
   P1 = points3D[0]
   P2 = points3D[1]
   P3 = points3D[2]
   P4 = points3D[3]

   erreurs = []
   nb_sol = 0

   for i in range(len(solutions)) : 
      R = solutions[i,:,1:] 
      C = solutions[i,:,:1]

      if not torch.all(R==torch.zeros((3,3))) : 
        nb_sol += 1 
        print("------------ Solution n° : ",nb_sol,"----------------")
        print("R = \n",R,)
        print("T = \n",C,)

        p1_P3P = torch.reshape(projection3D2D(P1,C,R,A),(1,2))
        p2_P3P = torch.reshape(projection3D2D(P2,C,R,A),(1,2))
        p3_P3P = torch.reshape(projection3D2D(P3,C,R,A),(1,2))
        p4_P3P = torch.reshape(projection3D2D(P4,C,R,A),(1,2))
        pt_2D_P3P = torch.cat((p1_P3P,p2_P3P,p3_P3P,p4_P3P),dim=0)    # (4,2)

        erreurs.append([0])
        for j in range(len(points2D)):
            erreur_pt = distance(points2D[j],pt_2D_P3P[j])
            erreurs[i]+=erreur_pt
        
   indice_min = 0
   min = erreurs[0]
   for i in range(1,len(erreurs)) :
    if erreurs[i]<min :
      min = erreurs[i]
      indice_min = i

   R_opti = solutions[indice_min,:,1:] 
   C_opti = solutions[indice_min,:,:1]
   print("\n------------ Best solution : ----------------")
   print("Solution n° :",indice_min+1,"\n")
   print("R estimé = \n", R_opti,"\n")
   print("T estimé = \n", C_opti, "\n")

In [ ]:
affichage_erreur(solutions, [p1, p2, p3, p4], [P1,P2,P3, P4], A)