In [17]:
import numpy as np 
import torch

batch_size = 5 

At first we have : 
- camera's parameters -> A (focal, center) 
- rotation matrix  -> R 
- position matrix -> C 
- 3D points position ->  P1 P2 P3 (and P4 to determinate the best solution after P3P)

In [18]:
# This script defines the camera parameters, rotation matrix, and translation matrix.
def camera() : 
  # Definition of the camera parameters
  # focal length
  fx = 800
  fy = 800
  # center
  cx = 320 
  cy = 240

  A = torch.tensor([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=torch.float64) # intraseca matrix of the camera (3*3)
  #A = torch.from_numpy(A)  # Convert to a PyTorch tensor
  print("A = \n", A)
  print(A.shape)  # (3*3)
  A_batch = A.repeat(batch_size,1,1)
  print("A_batch = \n", A_batch)
  print(A_batch.shape)  # (batch_size, 3, 3)
  return A_batch

A = camera() 



def rotation_matrix() : 
  # Definition of the rotation matrix of the camera 
  R = torch.tensor([[1, 0, 0],[0, -1, 0], [0, 0, -1]], dtype=torch.float64)  # (3*3)
  #R = torch.from_numpy(R)  # Convert to a PyTorch tensor
  print("R = \n",R)
  print(R.shape)  # (3*3)
  R_batch = R.repeat(batch_size,1,1)  # Repeat the rotation matrix for each batch
  print("R_batch = \n", R_batch)  
  print(R_batch.shape)  # (batch_size, 3, 3)
  return R_batch

def camera_position() : 
  # Definition of the translation matrix of the camera (the position)
  C = torch.tensor([[0,0,6]], dtype=torch.float64)    # T = [tx,ty,tz]  (1*3)
  print("C = \n",C)
  print(C.shape)  # (1*3)

  C_batch = C.repeat(batch_size, 1)  # Repeat the translation vector for each batch
  print("C_batch = \n", C_batch)  
  print(C_batch.shape)  # (batch_size, 3)

 
  return C_batch

R = rotation_matrix()
C = camera_position()

A = 
 tensor([[800.,   0., 320.],
        [  0., 800., 240.],
        [  0.,   0.,   1.]], dtype=torch.float64)
torch.Size([3, 3])
A_batch = 
 tensor([[[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]],

        [[800.,   0., 320.],
         [  0., 800., 240.],
         [  0.,   0.,   1.]]], dtype=torch.float64)
torch.Size([5, 3, 3])
R = 
 tensor([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]], dtype=torch.float64)
torch.Size([3, 3])
R_batch = 
 tensor([[[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.]],

        [[ 1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -1.

In [19]:
# Definition of 3D points in the world coordinate system
def point3Daleatoire(x) :
  # Generation of one random points in 3D space 
  return torch.tensor([[np.random.uniform(-x,x),np.random.uniform(-x,x),np.random.uniform(-x,x)]])

def pts_3D_4pts():
  # Generate randomly 4 3D points
  # Output : tensor which concatenate the 4 points = [ P1, P2, P3, P4 ] 

  P1 = point3Daleatoire(2)     # (1*3) -> pour P3P
  P2 = point3Daleatoire(2)
  P3 = point3Daleatoire(2)
  P4 = point3Daleatoire(2)
  
  points3D = torch.cat((P1,P2,P3,P4),dim=0);     # (LIGNES 4* COLONNES 3) - xyz
  print("points3D = \n", points3D)
  print(points3D.shape)  # (4*3)

  
  return points3D

def pts_3D_4pts_batch():
  # Generate randomly 4 3D points for each batch
  # Output : array which concatenate the 4 points = [ P1, P2, P3, P4 ] for each batch

  # Generate a batch of random points in 3D space
  # Each point is generated independently for each batch

  points3D_batch = torch.stack([pts_3D_4pts() for i in range(batch_size)])  # (batch_size, 4, 3)
  print("points3D_batch = \n", points3D_batch)
  print(points3D_batch.shape)  # (batch_size, 4, 3)
  return points3D_batch

points3D_batch = pts_3D_4pts_batch()  # Generate the batch of 3D points
'''
P1 = torch.tensor([0.7161, 0.5431, 1.7807], dtype=torch.float64)    # (3,)
P2 = torch.tensor([-1.1643, 0.8371, -1.0551], dtype=torch.float64)
P3 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64)
P4 = torch.tensor([-1.5224, 0.4292, -0.1994], dtype=torch.float64) 
'''
P1 = points3D_batch[:, 0, :]  # Extract P1 for each batch
P2 = points3D_batch[:, 1, :]  # Extract P2 for each batch
P3 = points3D_batch[:, 2, :]  # Extract P3 for each batch
P4 = points3D_batch[:, 3, :]  # Extract P4 for each batch

print("P1 = \n", P1_batch)
print(P1.shape)  # (batch_size, 3)


points3D = 
 tensor([[ 0.5809, -0.1600, -0.2529],
        [-0.9100, -0.1778,  0.0302],
        [ 0.4908,  1.0280, -0.3566],
        [ 1.8488, -0.7180, -0.9518]])
torch.Size([4, 3])
points3D = 
 tensor([[ 0.6384, -1.7285, -0.6817],
        [-0.1626, -0.0539, -1.1291],
        [-0.2243, -1.9960, -1.4533],
        [ 1.0999,  0.9221,  1.6678]])
torch.Size([4, 3])
points3D = 
 tensor([[-0.7532,  1.4582, -1.5701],
        [-1.2716,  0.6983, -0.5325],
        [-0.6419, -0.0864, -0.4413],
        [-1.8953,  1.7584, -0.0053]])
torch.Size([4, 3])
points3D = 
 tensor([[-1.8223, -1.2637,  1.7288],
        [-1.6803,  0.9148,  0.2451],
        [ 0.6108,  1.1212,  1.9780],
        [ 0.9886, -1.7289,  0.2284]])
torch.Size([4, 3])
points3D = 
 tensor([[ 1.3985,  1.5775, -1.3829],
        [-0.4063, -0.9708,  0.9838],
        [-1.1582,  0.6216, -0.3719],
        [-1.4580, -1.2597, -0.6311]])
torch.Size([4, 3])
points3D_batch = 
 tensor([[[ 0.5809, -0.1600, -0.2529],
         [-0.9100, -0.1778,  0.0302],


We create the 3 direction features vectors f1, f2, f3

In [20]:
def features_vectors(points3D,C, R,batch_size) :
    '''
    This function computes the features vectors for P3P algorithm.
    args:
    points3D : array with the 4 3D points = [ P1, P2, P3, P4 ] (4*3) 
    but we only use the first three points for P3P
    C: camera position matrix : (3*1)
    returns:
    featuresVect : array with the features vectors (9*1)
    '''
    P1 = torch.reshape(points3D[0], (batch_size,3,1))  # Reshape to (3,1) for easier calculations
    print("P1 = \n", P1)  # Print P1 to check the values
    print(P1.shape)  # (batch_size, 3, 1)
    P2 = torch.reshape(points3D[1], (batch_size,3,1))
    P3 = torch.reshape(points3D[2], (batch_size,3,1))

    C = torch.reshape(C, (batch_size,3,1))  # Reshape C to (3,1) for easier calculations
    print("C = \n", C)  # Print C to check the values
    print(C.shape)  # (batch_size, 3, 1)

    v1 = torch.matmul(R,(P1 - C))  # Calculate the vector from camera to P1
    print("v1 = \n", v1)  # Print v1 to check the values
    print(v1.shape)  # (batch_size, 3, 1)
    v2 = torch.matmul(R,(P2 - C))  # Calculate the vector from camera to P2
    v3 = torch.matmul(R,(P3 - C))  # Calculate the vector from camera to P3

    f1 = v1 / torch.norm(v1,dim=1, keepdim=True)  # Normalize the vector v1
    f2 = v2 / torch.norm(v2,dim=1, keepdim=True)  # Normalize the vector v2
    f3 = v3 / torch.norm(v3,dim=1, keepdim=True)  # Normalize the vector v3

    print("f1 = \n", f1)  # Print f1 to check the values
    print(f1.shape)  # (batch_size, 3, 1)

    f1 = torch.reshape(f1, (batch_size,1,3))  # Reshape to (3,1)
    print("f1 : ",f1.shape) # (batch_size,1,3)
    f2 = torch.reshape(f2, (batch_size,1,3))
    f3 = torch.reshape(f3, (batch_size,1,3))

    featuresVect = torch.cat((f1,f2,f3),dim=1)
    print("features vectors = \n",featuresVect)
    print(featuresVect.shape)  # (batch_size, 3, 3)

    return featuresVect # Return the features vectors need in P3P


points3D = [P1_batch, P2_batch, P3_batch]  # We define the points3D with the first three points
print("points3D = \n", points3D)  # Print the points3D to check the values  / List len = 3 


featuresVect = features_vectors(points3D, C, R,batch_size)  

points3D = 
 [tensor([[-0.4147,  0.2234, -1.1711],
        [ 0.9477, -0.2189,  1.8360],
        [-0.6812,  0.7641, -0.0831],
        [-1.3915, -0.9533,  1.5606],
        [-1.5090,  1.4747, -0.2659]]), tensor([[-1.5163,  1.7661,  1.0130],
        [ 0.3697,  0.9377,  0.5091],
        [-1.8278, -0.8189, -0.1363],
        [-0.6372,  0.4595,  0.1571],
        [ 0.9308, -0.9215, -0.4567]]), tensor([[-0.2264, -1.4611,  1.2904],
        [ 1.8173, -0.3789,  0.5046],
        [-1.9600, -0.9082,  0.7163],
        [-0.9605,  0.5930,  0.7639],
        [ 0.1188, -0.3083, -1.3033]])]
P1 = 
 tensor([[[-0.4147],
         [ 0.2234],
         [-1.1711]],

        [[ 0.9477],
         [-0.2189],
         [ 1.8360]],

        [[-0.6812],
         [ 0.7641],
         [-0.0831]],

        [[-1.3915],
         [-0.9533],
         [ 1.5606]],

        [[-1.5090],
         [ 1.4747],
         [-0.2659]]])
torch.Size([5, 3, 1])
C = 
 tensor([[[0.],
         [0.],
         [6.]],

        [[0.],
         [0.],
   

Lastly we need the functions to resolve the polynomial roots. - for test go to test resolution polynome 

In [21]:
from complex_utils import *


def polynomial_root_calculation_4th_degree_ferrari(a): # Ferrari's Method
    # Solving a polynomial of 4th degree

    # Input : array 5*1 with the 5 coefficiants of the polynomial 
    # Output : roots of the polynomial a[4]*x^4 + a[3]*x^3 + a[2]*x^2 + a[1]*x + a[0]   -> array : [x1,x2,x3,x4]  (4*1)

    if a.numel() != 5 :
      print("Expeted 5 coefficiants for a 4th order polynomial")
      return

    a0, a1, a2, a3, a4 = a      # float

    # Reduce the quartic equation to the form : x^4 + a*x^3 + b*x^2 + c*x + d = 0
    a = a3/a4           # float 
    b = a2/a4
    c = a1/a4
    d = a0/a4

    # Computation of the coefficients of the Ferrari's Method
    S = a/4
    b0 = d - c*S + b* S**2 - 3* S**4
    b1 = c - 2*b*S + 8*S**3
    b2 = b - 6 * S**2


    # Solve the cubic equation m^3 + b2*m^2 + (b2^2/4  - b0)*m - b1^2/8 = 0
    x_cube = polynomial_root_calculation_3rd_degree(1,b2,(b2**2)/4-b0,(-b1**2)/8)
    

    # Find a real and positive solution
    alpha_0_nul = True
    for r in x_cube :
      if torch.isclose(r[1],torch.tensor(0.0,dtype=torch.float64),atol=1e-7) and r[0] > 0 :
        alpha_0 = r
        alpha_0_nul = False
        

    if alpha_0_nul == False :   # case where we found a real and positive solution so alpha_0_imag = 0 
        alpha0_div_2 = product_complex_real(alpha_0,0.5)
        sqrt_alpha = sqrt(alpha0_div_2[0])
        term = addition_complex_real(- alpha0_div_2 ,-b2 / 2)
        denom = 2 * torch.sqrt(2 * alpha_0)
        
       
        frac = division_2_complex_numbers(torch.tensor([b1, 0.0]), denom)  # b1 is real, so we can use a tensor with 0 imaginary part

        x1 = addition_complex_real(sqrt_alpha ,- S) + sqrt_complex(addition(term,-frac))
        x2 = addition_complex_real(sqrt_alpha, - S) - sqrt_complex(addition(term,-frac))
        x3 = addition_complex_real(-sqrt_alpha, - S) + sqrt_complex(addition(term,frac))
        x4 = addition_complex_real(-sqrt_alpha,- S) - sqrt_complex(addition(term,frac))
    
    else:

        sqrt_inner1 = sqrt((b2**2) / 4 - b0)        # complex 
        x1 = addition_complex_real(sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x2 = addition_complex_real(- sqrt_complex(addition_complex_real(sqrt_inner1,-b2 / 2)),-S)
        x3 = addition_complex_real(sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)
        x4 = addition_complex_real(- sqrt_complex(addition_complex_real(- sqrt_inner1,-b2 / 2 )),-S)

    return [x1, x2, x3, x4]




We have all the variables needed for the p3p so we start

1. Storage of points : already done 

In [22]:
print("P1 = \n", P1)
print("P2 = \n", P2)
print("P3 = \n", P3)

P1 = 
 tensor([[ 0.5809, -0.1600, -0.2529],
        [ 0.6384, -1.7285, -0.6817],
        [-0.7532,  1.4582, -1.5701],
        [-1.8223, -1.2637,  1.7288],
        [ 1.3985,  1.5775, -1.3829]])
P2 = 
 tensor([[-0.9100, -0.1778,  0.0302],
        [-0.1626, -0.0539, -1.1291],
        [-1.2716,  0.6983, -0.5325],
        [-1.6803,  0.9148,  0.2451],
        [-0.4063, -0.9708,  0.9838]])
P3 = 
 tensor([[ 0.4908,  1.0280, -0.3566],
        [-0.2243, -1.9960, -1.4533],
        [-0.6419, -0.0864, -0.4413],
        [ 0.6108,  1.1212,  1.9780],
        [-1.1582,  0.6216, -0.3719]])


2. Storage of the features vectors : done

In [23]:
# we got featuresVect and we access the 3 values 
f1 = featuresVect[:,0,:]  # Access the first feature vector for each batch
f2 = featuresVect[1]
f3 = featuresVect[2]

print("f1 = ", f1)
print(f1.shape)  # (batsh_size,3)
print("f2 = ", f2)
print("f3 = ", f3)

f1 =  tensor([[-0.0577, -0.0311,  0.9978],
        [ 0.2216,  0.0512,  0.9738],
        [-0.1104, -0.1239,  0.9861],
        [-0.2930,  0.2007,  0.9348],
        [-0.2282, -0.2231,  0.9477]], dtype=torch.float64)
torch.Size([5, 3])
f2 =  tensor([[ 0.2216,  0.0512,  0.9738],
        [ 0.0662, -0.1680,  0.9836],
        [ 0.3133,  0.0653,  0.9474]], dtype=torch.float64)
f3 =  tensor([[-0.1104, -0.1239,  0.9861],
        [-0.2832,  0.1269,  0.9506],
        [-0.3434,  0.1591,  0.9256]], dtype=torch.float64)


3. Création of a solution variable : maximum 4 solutions  

    Matrix (4,3,4)  
    Each layer is a solution, for each leayer : first column stres the camera position matrix C (3,1) and the remaining 3 columns store the rotation matrix R (3,3)

In [24]:
solutions = torch.zeros((batch_size,4,3,4), dtype=torch.float64)
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

solutions = 
 tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
        

4. Verification that the 3 points given are not collinear 

In [ ]:
# Test of non-collinearity
v1 = P2 - P1
v2 = P3 - P1
if torch.norm(torch.cross(v1,v2, dim=0))==0 :
    print('Problem: the points must not be collinear')
else:
    print('The points are not collinear, we can continue')

The points are not collinear, we can continue


5. Creation of an orthonormal frame from f1, f2, f3 (the features vectors)

In [ ]:
# Calculation of vectors of the base τ = (C,tx,ty,tz)
tx = f1     
print("tx = ", tx)
print(tx.shape)  # (3,)
tz = torch.cross(f1,f2)/torch.norm(torch.cross(f1,f2))
print("tz = ", tz)
ty = torch.cross(tz,tx)
print("ty = ", ty)

Display for the verification of non-collinearity of the 3 vectors 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
print("tx =", tx)
print("ty =", ty)
print("tz =", tz)

print("\nVérification orthogonalité :")
print("tx · ty =", np.dot(tx, ty))
print("tx · tz =", np.dot(tx, tz))
print("ty · tz =", np.dot(ty, tz))

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

origin = np.zeros(3)

ax.quiver(*origin, *tx, color='r', label='tx')
ax.quiver(*origin, *ty, color='g', label='ty')
ax.quiver(*origin, *tz, color='b', label='tz')

ax.set_xlim([-1, 1])
ax.set_ylim([-1, 1])
ax.set_zlim([-1, 1])

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('Base τ (tx, ty, tz)')
ax.legend()
plt.show()


5. (bis) Creation of a transformation matrix T and expression of the f3 vector in this frame

In [ ]:
tx = torch.reshape(tx,(1,3))   # (1*3)
ty = torch.reshape(ty,(1,3))
tz = torch.reshape(tz,(1,3))

# Computation of the matrix T and the feature vector f3
T = torch.cat((tx,ty,tz),dim = 0) # (3*3)
f3_T = torch.tensordot(T,f3, dims=1) # (3,)

print("tx = \n", tx)
print(tx.shape)  # (1*3)
print("ty = \n", ty)
print("tz = \n", tz)
print("f3_T = \n", f3_T)
print(f3_T.shape)  # (3,)
print("T = \n", T)
print(T.shape)  # (3,3)

The sing of the z-coordinate in f3_T give us the sign of teta, that we will need after 

In [ ]:
f3_T_positif = False

# Having teta in [ 0, pi ] 
if f3_T[2] > 0 :
    f3_T_positif = True
   

6. Change of frame is performed on the 3D points side, and the transformation matrix N is defined

In [ ]:
# Calculation of vectors of the base η = (P1,nx,ny,nz)
nx = (P2 - P1)/torch.norm(P2 - P1)      #(3,)
nz = torch.cross(nx,P3-P1)/torch.norm(torch.cross(nx,P3-P1), dim=0)  
ny = torch.cross(nz,nx)
print("nx = ", nx)
print(nx.shape)  # (3,)
print("ny = ", ny)
print("nz = ", nz)

# Reshape the vectors to (1,3) for concatenation
nx = torch.reshape(nx,(1,3))  # (1,3)
ny = torch.reshape(ny,(1,3))
nz = torch.reshape(nz,(1,3))
print("nx = \n", nx)
print(nx.shape)  # (1*3)
print("ny = \n", ny)
print("nz = \n", nz)

# Computation of the matrix N and the world point P3
N = torch.cat((nx,ny,nz),dim = 0) # (3*3) T's equivalent in the world coordinate system

P3_n = torch.tensordot(N,P3-P1, dims=1) # (3,)

print("N = \n", N)
print(N.shape)  # (3,3)
print("P3_n = \n", P3_n)
print(P3_n.shape)  # (3,)


7. Definition of the variables for the following steps 

In [ ]:
# Computation of phi1 et phi2 with 0=x, 1=y, 2=z
phi1 = f3_T[0]/f3_T[2]
phi2 = f3_T[1]/f3_T[2]
print("phi1 = ", phi1)
print("phi2 = ", phi2)

# Extraction of p1 and p2 from P3_eta
p1 = P3_n[0] #x
p2 = P3_n[1] #y
print("p1 = ", p1)
print("p2 = ", p2)

# Computation of d12
d12 = torch.norm(P2-P1)
print("d12 = ", d12)

# Computation of b = cot(beta)
cosBeta = torch.dot(f1,f2)/(torch.norm(f1)*torch.norm(f2)) 
print("cosBeta = ", cosBeta)  
b = torch.sqrt(1/(1-cosBeta**2)-1)

if cosBeta < 0 :
    b = -b
print("b = ", b)

8. Calculation of the coefficients of the polynomial 

In [ ]:
a4 = - phi2**2 * p2**4 - phi1**2 * p2**4 - p2**4
a3 = 2 * p2**3 * d12 * b + 2 * phi2**2 * p2**3 * d12 * b - 2 * phi1 * phi2 * p2**3 * d12
a2 = - phi2**2 * p1**2 * p2**2 - phi2**2 * p2**2 * d12**2 * b**2 - phi2**2 * p2**2 * d12**2 + phi2**2 * p2**4 + phi1**2 * p2 **4 + 2 * p1 * p2**2 * d12 + 2 * phi1 * phi2 * p1 * p2**2 * d12 * b - phi1**2 * p1**2 * p2**2 + 2 * phi2**2 * p1 * p2**2 * d12 - p2**2 * d12**2 * b**2 - 2 * p1**2 * p2**2
a1 = 2 * p1**2 * p2 * d12 * b + 2 * phi1 * phi2 * p2**3 * d12 - 2 * phi2**2 * p2**3 * d12 * b - 2 * p1 * p2 * d12**2 * b
a0 = - 2 * phi1 * phi2 * p1 * p2**2 * d12 * b + phi2**2 * p2**2 * d12**2 + 2 * p1**3 * d12 - p1**2 * d12**2 + phi2**2 * p1**2 * p2**2 - p1**4 - 2 * phi2**2 * p1 * p2**2 * d12 + phi1**2 * p1**2 * p2**2 + phi2**2 * p2**2 * d12**2 * b**2

print("a4 = ", a4)
print("a3 = ", a3)
print("a2 = ", a2)
print("a1 = ", a1)
print("a0 = ", a0)


9. Recovery of the polynomial roots cos (teta)

In [ ]:
# Computation of the roots
roots = polynomial_root_calculation_4th_degree_ferrari(torch.tensor([a0,a1,a2,a3,a4])) # (4,)

print("roots = \n", roots)  # list of tensor (for complex numbers)


10. For each solution : computation of the camera position and rotation matrix

In [ ]:
# For each solution of the polynomial
for i in range(4):
  #if np.isclose(np.imag(roots[i]),0) : # if real solution 

    # Computation of trigonometrics forms
    cos_teta = torch.tensor(roots[i][0])# real part of the root 
    sin_teta = torch.sqrt(1-cos_teta**2)

    cot_alpha = ((phi1/phi2)*p1 + cos_teta*p2 -d12*b )/ ((phi1/phi2)*cos_teta* p2 - p1 + d12)

    sin_alpha = torch.sqrt(1/(cot_alpha**2+1))
    cos_alpha= torch.sqrt(1-sin_alpha**2)

    if cot_alpha < 0 :
      cos_alpha = -cos_alpha

    # Computation of the intermediate rotation's matrixs
    C_estimate = torch.tensor([d12*cos_alpha*(sin_alpha*b + cos_alpha), d12*sin_alpha*cos_teta*(sin_alpha*b+cos_alpha), d12*sin_alpha*sin_teta*(sin_alpha*b+cos_alpha)]) # (3,)
    print("C_estimate = \n", C_estimate)
    print(C_estimate.shape)  # (3,)
    Q = torch.tensor([[-cos_alpha, -sin_alpha*cos_teta, -sin_alpha*sin_teta], [sin_alpha, -cos_alpha*cos_teta, -cos_alpha*sin_teta], [0, -sin_teta, cos_teta]])    # (3*3)
    print("Q = \n", Q)
    print(Q.shape)  # (3,3)
    # Computation of the absolute camera center
  
    C_estimate = P1 + torch.tensordot(torch.transpose(N, 0,1), C_estimate, dims=1) # (3,)
    print("C_estimate = \n", C_estimate) 
    print(C_estimate.shape)  # (3,)
    C_estimate = torch.reshape(C_estimate, (3,1))  # Reshape to (3,1) for consistency
    print("C_estimate = \n", C_estimate)  # (3,1)
    print("C_estimate.shape = ", C_estimate.shape)  # (3,1)

    # Computation of the orientation matrix
    R_estimate = torch.tensordot(torch.tensordot(torch.transpose(N,0,1),torch.transpose(Q, 0,1), dims=1),T,dims=1)   # (3*3)
    print("R_estimate = \n", R_estimate)
    print(R_estimate.shape)  # (3,3)
    
    # Adding C and R to the solutions
    solutions[i,:,:1]= C_estimate
    solutions[i,:,1:] = R_estimate

print("solutions = \n", solutions)


In [ ]:
print("solutions = \n", solutions)
print(solutions.shape)  # (4,3,4)

11. Reprojection of points in 2D from the newly estimated matrices to verify the estimation error.

In [ ]:
def projection3D2D(point3D,C,R,A) :
  # 3D point = [ Xw, Yw, Zw ]'   (1*3)
  # T : camera translation matrix : (3*1)
  # R : camera rotation matrix : (3*3)
  # A : intraseca matrix of the camera : (3*3)
  # Output : return the coordonates of the point in 2D 

  PI = torch.cat((torch.eye(3, dtype=torch.float64),torch.zeros((3,1), dtype=torch.float64)),dim=1)  # (3*4)

  Rt = torch.cat((R,C),dim=1)               # (3*4)
  Rt = torch.cat((Rt,torch.tensor([[0,0,0,1]], dtype=torch.float64)),dim=0)   # (4*4)

  point3D_bis = torch.cat((torch.reshape(point3D,(3,1)),torch.tensor([[1]],dtype=torch.float64)),dim=0)   #(4*1)
  
  point2D = torch.tensordot(torch.tensordot(torch.tensordot(A,PI,dims=1),Rt,dims=1),point3D_bis,dims=1)  # 2D point = [u, v, w] (3*1)
  point2D = point2D / point2D[2]        # 2D point = [u, v, 1] (3*1)
  return point2D[:2]


C_transpose = torch.transpose(C, 0, 1)  # (3*1) -> (1*3)

p1 = projection3D2D(P1,C_transpose,R,A)
print("p1 = ", p1)
print(p1.shape)  # (2,1)
p2 = projection3D2D(points3D[1],C_transpose,R,A)
print("p2 = ", p2)
p3 = projection3D2D(points3D[2],C_transpose,R,A)
print("p3 = ", p3)
p4 = projection3D2D(P4,C_transpose,R,A)
print("p4 = ", p4)




12. Calculation of errors = distance between the 2D points estimated from the found rotation and position matrices and the 2D points from the initial matrices

In [ ]:
def distance(pt, pt_estimation):
    erreur = torch.tensor(0, dtype=torch.float64)  # Initialize error as a tensor
    for i in range(len(pt)): 
      erreur = erreur + torch.tensor((pt[i] - pt_estimation[i])**2, dtype=torch.float64)  # Ensure each term is a tensor
      #erreur += (pt[i] - pt_estimation[i])**2
    return torch.sqrt(erreur)



def affichage_erreur(solutions,points2D,points3D,A) : 
   # Compute the error of estimation for each points after the P3P algorithm 

   # solutions : solution matrix returned by P3P (4*3*4)
   # points 3D : 4 pts 3D used for P3P 
   # points 2D : 4 pts 2D used for P3P (image of the 3D points)
   
   P1 = points3D[0]
   P2 = points3D[1]
   P3 = points3D[2]
   P4 = points3D[3]

   erreurs = []
   nb_sol = 0

   for i in range(len(solutions)) : 
      R = solutions[i,:,1:] 
      C = solutions[i,:,:1]

      if not torch.all(R==torch.zeros((3,3))) : 
        nb_sol += 1 
        print("------------ Solution n° : ",nb_sol,"----------------")
        print("R = \n",R,)
        print("T = \n",C,)

        p1_P3P = torch.reshape(projection3D2D(P1,C,R,A),(1,2))
        p2_P3P = torch.reshape(projection3D2D(P2,C,R,A),(1,2))
        p3_P3P = torch.reshape(projection3D2D(P3,C,R,A),(1,2))
        p4_P3P = torch.reshape(projection3D2D(P4,C,R,A),(1,2))
        pt_2D_P3P = torch.cat((p1_P3P,p2_P3P,p3_P3P,p4_P3P),dim=0)    # (4,2)

        erreurs.append([0])
        for j in range(len(points2D)):
            erreur_pt = distance(points2D[j],pt_2D_P3P[j])
            erreurs[i]+=erreur_pt
        
   indice_min = 0
   min = erreurs[0]
   for i in range(1,len(erreurs)) :
    if erreurs[i]<min :
      min = erreurs[i]
      indice_min = i

   R_opti = solutions[indice_min,:,1:] 
   C_opti = solutions[indice_min,:,:1]
   print("\n------------ Best solution : ----------------")
   print("Solution n° :",indice_min+1,"\n")
   print("R estimé = \n", R_opti,"\n")
   print("T estimé = \n", C_opti, "\n")

In [ ]:
affichage_erreur(solutions, [p1, p2, p3, p4], [P1,P2,P3, P4], A)